### ISSUE TITLE
Volet angle marge - angles possibles

### ISSUE THREAD

**Issue by Alexisbou** [guyfrancoeur/INF3135_H2020#109]
Bonjour à tous,

De ce que je comprends, l'information suivante:

**la tolérance entre les volets (gauche vs droite)
    0.5**
signifie la tolérance des angles des volets. Par contre, serait-il utile de savoir entre quelles balises les angles peuvent se trouver pour les volets? (Ex. angle maximum se retrouve entre 0 et 90).

**Comment by cryptoswarm** [comment]
Au décollage : Braquage des volets 15°.
 À l'atterrissage : Braquage des volets 50°.

 selon ce que j'ai lu, cet angle dans la plupart des avions est comprise entre 5° et 15°.

Alors que lors de l'atterrissage cet angle est comprise entre 25° et 40° .

hope this info will be helpful.

**Comment by guyfrancoeur** [comment]
Bonjour,

Nous n'avons pas a gérer `volet_angle_mage` 
Volet_angle_marge_XX sera enlevé de flop.h.

Cordialement,
