### ISSUE TITLE
TP2 : Quel fichier zip utiliser ?

### ISSUE THREAD

**Issue by link852258** [guyfrancoeur/INF3135_H2020#110]
Dans l'énoncé du TP2 vous dites, dans les contraintes, d'utiliser les fichiers flop.h et flop.c de tp1.zip, mais il y a un tp2.zip avec un fichier flop.h et flop.o, donc faut-il utiliser les fichiers de tp1.zip ou tp2.zip?

**Comment by guyfrancoeur** [comment]
Allo,

Je vais vérifier, l'énoncé!  tp2.zip svp.

Cordialement,

G
