### ISSUE TITLE
Entrée 02 - capteurs d'angle d'incidence

### ISSUE THREAD

**Issue by julienbigras1** [guyfrancoeur/INF3135_H2020#111]
Dans la transaction d'entrée 02: Lecture d'un des capteurs d'angle d'incidence. 

D'après ce que j'ai compris, il y a 2 capteurs d'angle d'incidence. Donc, A1 serait le premier capteur et A2 serait le deuxième capteur. Pourquoi il y a aussi un capteur A3? 
 Parce que A3 dans l'exemple est mis comme s'il pouvait exister.

**Comment by guyfrancoeur** [comment]
Allo,

C'est une capteur additionnel (backup). 
Il est important lorsque A1 ou A2 est en ERREUR.

Cordialement,

G
