### ISSUE TITLE
TP2 : Make tp1, quelle archive utiliser ?

### ISSUE THREAD

**Issue by link852258** [guyfrancoeur/INF3135_H2020#112]
Bonjour
Lorsqu'on refait l'executable du tp1 est-ce qu'on doit utiliser les fichiers flop.o et flop.h de l'archive tp2.zip ou de l'archive tp1.zip?
Merci.

**Comment by hydraslahir** [comment]
Il serait préférable d'utiliser tp2.zip, https://github.com/guyfrancoeur/INF3135_H2020/issues/110
