### ISSUE TITLE
question MCAS déactivé

### ISSUE THREAD

**Issue by LorenaMedina** [guyfrancoeur/INF3135_H2020#114]
L'énoncé indique : MCAS doit être déactivé lorsqu'un **système est en erreur**; 

- La définition de **système en erreur** est : 
  + cas1 : le capteur donne une troisième manifestation de ERROR; 
  + cas2 : capteur donne une valeur inacceptable
  + cas3 : Erreur provenant d'un autre système avec la trx 05 ?
- Existe-t-il d'autre cas autre que des transactions 05 qui concernent **un autre système** ?

Merci.

**Comment by guyfrancoeur** [comment]
Bonjour,

Réponse à suivre!
