### ISSUE TITLE
question tolérance entre les volets

### ISSUE THREAD

**Issue by LorenaMedina** [guyfrancoeur/INF3135_H2020#115]
J'aimerais savoir la différence entre les 2 conditions de l’énoncé?.

- La tolérance entre les volets (gauche vs droite) :     0.5

- La tolérance entre les capteurs longueur des volets:   1.25

Merci

**Comment by guyfrancoeur** [comment]
Allo,

Très bonne question,

- ~~La tolérance entre les volets (angles) (gauche vs droite) : 0.5~~
  + n'est pas qqc que vous devez gérer, vieux a été enlevé dans le tp1.
- La tolérance entre les capteurs longueur des volets: 1.25
  + la longueur (ouverture) de la tolérance maximale entre les volets de Gauche et Droite.

Voila.

G

Réagisez a ce post.
