### ISSUE TITLE
problem de decompression de tp2.zip 

### ISSUE THREAD

**Issue by cryptoswarm** [guyfrancoeur/INF3135_H2020#116]
c'est ce que je reçois quand j'essaie de decompresser  tp2.zip
`Archive:  tp2.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of tp2.zip or
        tp2.zip.zip, and cannot find tp2.zip.ZIP, period.`
le fichier tp2.zip a de l'air d'être corrupted 
what's the problem ? 
any hint?

**Comment by benoit-dubreuil** [comment]
Ça m'est arrivé durant le TP1 quand je downloadais l'archive avec `wget`. Je me suis tanné et j'ai juste téléchargé l'archive à l'aide de Firefox et ça l'a fonctionné.

**Comment by guyfrancoeur** [comment]
Bonjour,

Utilisez-vous le mode binaire (raw) ?

Réagisez à ce post.
