### ISSUE TITLE
TP2 : question : <timestamp> et format de données

### ISSUE THREAD

**Issue by LorenaMedina** [guyfrancoeur/INF3135_H2020#117]
_Étant donné que les transactions des sorties ont besoin d'indiquer le : < timestamp >. _

Est-ce qu'on va recevoir en entrée des **lignes de données** toujours avec cette information et bon format ( <size_t> )?

Merci.

**Comment by guyfrancoeur** [comment]
Bonjour,

C'est dure a dire.  En théorie les systèmes qui produisent les données semble bon pour l'instant.
Mais je ne sais pas si c'est toujours vrai.
Afin de debuter le tp correctement on va dire que le type et les données sont du bonnes.
Seulement si vous avez du temps vous pourez conciderer les exceptions.

Cordialement

Réagisez à ce post.
