### ISSUE TITLE
Fermeture du programme?

### ISSUE THREAD

**Issue by riadsm** [guyfrancoeur/INF3135_H2020#118]
Comment on sait quand on doit fermer le programme.Est ce qu'il faut écrire une commande nous même dans l'entrée Standart ou on suppose que vous le fermez vous-même?

**Comment by benoit-dubreuil** [comment]
Je pense que le `tp2` doit s'arrêter lorsqu'il lit le caractère "end of file", si je comprends bien.

**Comment by guyfrancoeur** [comment]
Allo,

la fin du stream.

**Comment by cedricwtkUQAM** [comment]
Dois t'on arreter le programme lorsque l'on bute sur un format d'entree non valide? Par exemple si on entre un poeme en fichier d'entree, le contenu ne sera clairement pas valide. Tout comme si la transaction est une trx 01 alors il prends juste un parametre en plus.
Dans le cas ou une trx 01 a 2 parametres est ce que notre programme doit poursuivre?
