### ISSUE TITLE
Tests valides

### ISSUE THREAD

**Issue by GholamiMahmood** [guyfrancoeur/INF3135_H2020#119]
Bonjour
Est-ce qu'une méthode doit avoir le même résultat dans le tp1 et tp2  ? Par exemple la méthode volet_ouvert_vX   

Tp1: volet_ouvert_v1  (passed) 

Tp2: volet_ouvert_v1 (passed)

**Comment by guyfrancoeur** [comment]
Bonjour,

Je suis confu, besoin d'aide pour comprendre la question.

merci.
