### ISSUE TITLE
Gestion des erreurs multiples pour un même système

### ISSUE THREAD

**Issue by julienbigras1** [guyfrancoeur/INF3135_H2020#120]
Bonjour,
Est-ce que c'est possible d'avoir plusieurs erreurs différentes pour le même système? 

Si oui, est-ce que l'on tient en compte seulement de la première transaction qui indique que le système est de nouveau fonctionnel pour la première erreur ou l'on doit attendre l'ensemble des erreurs soient résolues dans ce système pour mentionner que celui-ci est de nouveau fonctionnel. 

Par exemple, dans l'énoncer, le cas 04 : timestamp = {176, 178, 179} donne un 1er cas d'erreurs (transaction de sortie 06) pour le système 12 (stabilisateur horizontal). Un peu après dans la lecture d'une transaction d'entrée 05 qui contient: "198 05 12 2"
> > `GF` je vais changer l'exemple pour prendre un autre nombre que 12 --> 16.
> > revoir l'énoncé pour me dire si c'est mieux.
> > les trx <timestamp> 05 [11-14] <code_erreur> sont très improbable.

nous donne aussi une autre erreur pour ce même système. Doit-on attendre d'avoir "07 12 179" et "07 12 198" ou seulement le premier arrivé pour remettre ce système fonctionnel?
> > `GF` ici je ne comprend pas. seul une trx 05 peu reinitialiser une 05 trx.

Les deux choix pourraient être possibles, mais selon le choix pris, ça change l'ordre d'activation et de désactivation du MCAS.

**Comment by guyfrancoeur** [comment]
Bonjour,

Bonne question.

- Etes vous en mesure de gerer ce cas ?
- Quel est le but de la question ?
- Est-ce un cas possible ou impossible ?

Vous avez detecté qqc d'intéressant à vous de prendre une décision. De mon côté je vais réflchir aussi.

Merci.

Réagissez à ce post

**Comment by guyfrancoeur** [comment]
Allo,

Pour la deuxième portion de la question: 
Les transactions doivent être traité dans l'ordre d'arrivé.  Comme un stream de données continu.

Voila,

G
