### ISSUE TITLE
TP2 : Makefile - cible default

### ISSUE THREAD

**Issue by leopoldmaillard** [guyfrancoeur/INF3135_H2020#122]
On peut lire dans l'énoncé : "La commande make employée seule devra exécuter la cible default", sans plus de précision.

Doit-elle être simplement un équivalent à ```make tp2``` ?

**Comment by guyfrancoeur** [comment]
Allo,

Oui, je vais vérifier dans l'énoncé. ** oups il manque des mots **
Je vais compléter les mots qui manquent.
