### ISSUE TITLE
TP2 : Comment gérer une transaction 05 ou les cas qui se présentent ?

### ISSUE THREAD

**Issue by hydraslahir** [guyfrancoeur/INF3135_H2020#123]
## Quelle est la sortie d'une erreur 05 ?
Les sorties 06(détecte) et 07(récupère) ne considèrent pas les systèmes de 11 à 19, ce qui, à mon avis, est plutot dommage.

## exemple: 
* 145 05 12 37 // Erreur sur le systeme 12 avec valeur 37
  + --> 06 (pas 12(SH)) 145 (37?)
* 666 05 12 0 //Retour
  + --> 07 (toujours pas 12) 666 ( 0?)

Sinon, je peux simplement ne pas faire de sortie et ne jamais savoir quels systemes externes ont arrêté le MCAS (sauf avec GDB, biensur :wink:  )

**Comment by guyfrancoeur** [comment]
Bonjour,

Si la question est quel est la sortie pour une trx 05:

la réponse (sortie) est : 
 - une trx 06 : dans le cas ou le code erreur est != 0
 - une trx 07 : dans le cas ou le code erreur est == 0

il n'est très peu probable que des trx 05 arrivent de systèmes externes pour les codes {11,12,13,14} = {VOLET, SH, AI, ETAT}.  C'est notre système qui gere cela.

Cordialement,

G

Réagisez à ce post.

**Comment by hydraslahir** [comment]
* Supposons l'erreur 145 05 12 37
  Il est invalide et je produis 06 xxx 145 37 (où xxx est inconnu)
  Le message d'erreur que je produis dans ce cas précis n'est pas défini.

* ce que dit le TP : 
06 <système> <timestamp> [information additionnelle]
06 <VOLET=11,SH,AI,ETAT|[15-19]> <size_t> [ ... ]
** Aucune mention de systemeExtene **

* Systemes externes(05) = [11 - 19]
* Sortie 6 [11 = Volet, 12 =SH (...)]

**Comment by guyfrancoeur** [comment]
Allo,

Il est très peu probable que la trx 05 produise une erreur pour les systèmes 11, 12, 13, 14.

Ceci dit si 
145 05 16 37 //ok

vous générer un trx 06
06 16 145 37

système est : systeme connu et système externe (non nommé)

Cordialement,

G

**Comment by hydraslahir** [comment]
J'ai parfaitement compris tout ça.
Néanmoins, si 145 05 16 37 --> 07 16 145 37, alors comment je différentie

* 06 16 145 37 // Erreur ETAT = 1
* 06 16 145 47 // Systeme 16 non fonctionnel

**Comment by hydraslahir** [comment]
## Exemple No.145
Je vais recommencer. 
Je sais qu'un 05 (!=0) doit générer un 06

#### Les 3 cas suivant génèrent la même chose +/- le TimeStamp.
Supposons ceci:

    1 01 01 //Etat DECOLLAGE [2.5 , 51.0] 
    2 02 A1 3
    3 02 A2 50
    --> 06 13 3 MARGE  // Le AI produit une erreur MARGE au TS=3
et 

    400 05 13 90
    --> 06 13 400 90  // Le Systeme 13 a le code erreur 90 au TS=400

Ça ne vous ennuie pas que les deux codes en sorties possèdent 06 13, même s'ils ne signifient pas la même chose ?

**Comment by guyfrancoeur** [comment]
Allo,

Merci pour ta synthèse tu sembles avoir bien compris.

Voir ma réponse précédente ou les autres posts qui parlent du sujet.
- #123 (haut), #120, #114 (important)

> > `GF` en haut post précédent
> > il n'est très peu probable que des trx 05 arrivent de systèmes externes pour les codes
> > {11,12,13,14} = {VOLET, SH, AI, ETAT}. C'est notre système qui gere cela.

Il est très improbable que ceci arrive.  Car, les codes 11, 12, 13, 14 sont gérés par nous et non pas par des systèmes externes.
```
<timestamp> 05 [11-14] <code_erreur> // très improbable
```

NON, ça ne m’ennuie pas.  Dans la vie c'est fort possible. Il faut toujours tout garder, maintenir et lister, surtout dans le cas de systèmes critiques (aviation) afin de reconstituer les événements.

Si des informations sont jetées, il sera impossible de savoir ce qui c'est vraiment passé.

Pour vous programmer, je ne crois pas que ceci est un problème.  Ca ne créer aucune problématique de code.

Mais je sais très bien pourquoi vous (tous les étudiants, pas toi spécifiquement) demandez, posez les questions, afin de gérer les cas d'exceptions.  Je vais dire ceci, il ne faut pas gérer les cas d'exception au début.  Il faut les noter sur un papier (fichier). Par la suite, produire des sorties attendues.  Si vous **modularisez** le traitement (+1), vous faites un TDD avec cUnit (un test unitaire) qui vérifie la fonction.  Si la fonction n'est pas en mesure de traiter un seul `156 05 15 911` elle ne sera pas capable de traiter deux trx `... 05 15 ...`.  Ce cas existe deux `... 05 15 ...`. Oui, un système peut avoir plusieurs erreurs. Le moteur 3 est chaud et il tourne trop lentement.

Vous devez
0. faire un fichier générique de transactions;
1. faire le code, le programme, afin de traiter les transactions;
2. faire faire un fichier de sortie attendu.
3. faire un test qui vérifie la sortie obtenue et la sortie attendue
4. corriger le programme (ou ... pas)
5. rendre ceci automatique
6. ajouter un scénario 2, 3, 4 (d'autres fichiers trx)

On ne lâche pas.

G
