### ISSUE TITLE
TP2 : liste des fonctions valides

### ISSUE THREAD

**Issue by guyfrancoeur** [guyfrancoeur/INF3135_H2020#126]
Bonjour,

### Pour le tp2 (au moment de la production du post) :

```bash
./tp1 all | ./liste.sh | sort
```
```
angle_incidence_marge_v1
atterrissage_angle_conforme_v1
decollage_angle_conforme_v2
stabilisateur_horizontal_conforme_v3
stabilisateur_horizontal_marge_v3
tarmac_angle_conforme_v1
validation_etat_appareil_v3
vol_angle_conforme_v3
volet_ouverture_marge_v3
volet_ouvert_v2
```

### Pour le tp1 (minimum)
```bash
./tp1 | ./liste.sh | sort
```
```
angle_incidence_marge_v1
stabilisateur_horizontal_conforme_v3
tarmac_angle_conforme_v1
validation_etat_appareil_v3
volet_ouvert_v2
```

Utilisez le fichier tp2.zip 
Consultez [directement ici](https://github.com/guyfrancoeur/INF3135_H2020/issues/125#issue-578294788) information sur le fichier.

Si vous n'arrivez pas à ce résultat expliquez-moi pourquoi.

Réagissez à ce post.

**Comment by YounesJulien** [comment]
Bonjour Monsieur 

Juste pour l'ordre des tests dans `./tp1 all | ./liste.sh | sort` : 
Le `sort` devrai mettre `volet_ouvert_v2` avant `volet_ouverture_marge_v3` .

Merci pour les modifications :)

**Comment by guyfrancoeur** [comment]
Allo,

@YounesJulien Es-tu certain de cela ? Linux de UQAM est donc 🤒 ou 😈 

lol, lâche pas.

Réagissez à ce post.

**Comment by bachmaroua** [comment]
si on execute :   
./tp1 ( n'importe quoi autre que "ALL")  | ./liste.sh | sort

est ce que il doit afficher quand meme 

> angle_incidence_marge_v1
> stabilisateur_horizontal_conforme_v3
> tarmac_angle_conforme_v1
> validation_etat_appareil_v3
> volet_ouvert_v2


ou il doit afficher un message d'erreur indiquant que cette option n’existe pas
