### ISSUE TITLE
TP2 : Ordre des etats

### ISSUE THREAD

**Issue by Denowrrz** [guyfrancoeur/INF3135_H2020#127]
Bonjour je voudrais confirmer si les etats **doivent** passer de 0 a 4  en ordre , mais aussi si il peut passer de 4 à 0 sans restart.

 Merci.

**Comment by guyfrancoeur** [comment]
Bonjour,

L'état de l'avion est une information qui aide le programme dans la price de decision.

Ceci veut dire que si le pilot ne change pas l'état le MCAS sera en erreur souvent.
Ceci veut aussi dire que le MCAS sera innactif donc pas utile pour aider les pilots pour le voyage.

Bon fini les explications non technique.

L'état peut être n'importe quoi.  Il est souhaitable que les états changes graduellement.
Mais plus encore, est-ce un problème, pour le programmeur ou le programme,  s'ils ne changent pas adéquantement ? Est-ce que votre logiciel fonctionne toujours ? Est-il en mesure de s'exécuter même si on saute un état ?

Finalement, je ne peux pas garanatir (confirmer) ou répondre à la question par oui ou non.

Par contre, je peux garantir que ceci n'est pas un problème, et si c'est le cas veuillez me dire pourquoi.

Garder ca simple svp.

Cordialement,

Réagissez à ce post.

**Comment by Denowrrz** [comment]
Je comprend que tant que l'état s'incrémente graduelement il n'y a pas de problème sinon si il saute d'un etat  a l'autre sans prendre compte de l'incrémentation  il y aura erreur n.8. Donc le passage de 4 à 0 il n'y a pas de probleme.
