### ISSUE TITLE
TP2 : Correction de mon TP1, angle_incidence_marge_v1

### ISSUE THREAD

**Issue by benoit-dubreuil** [guyfrancoeur/INF3135_H2020#128]
Bonjour,

Je suis en train de corriger mon TP1 afin de pouvoir bien commencer le TP2.

Or, j'ai remarqué que mes tests pour la fonction `angle_incidence_marge_v1` contenue dans `flop.h` ne fonctionnent pas. Et, en regardant l'énoncé, je ne comprends pas. Alors, j'aimerais savoir si j'ai associé les bonnes exigences avec cette fonction.

L'exigence de la fonction `angle_incidence_marge_v1` est :
> la tolérance entre les capteurs d'angle d'incidence doit être inférieur ou égale à 0.250

Me trompe-je? Quand j'exécute `angle_incidence_marge_v1(0.0f, 0.251f)`, ça me donne `true`.

Merci,

**Comment by cedricwtkUQAM** [comment]
Utilise tu le nouveau flop.h? Dans mon cas je ne l'ai pas encore testé avec le nouveau fichier flop mais **assert true sur les valeurs entrées devraient etre fausses.**

**Comment by benoit-dubreuil** [comment]
Yep! J'utilise `flop.o` et `flop.h` du `tp2.zip` grâce à mon Makefile. Je vais réessayer à la main voir.

**Comment by benoit-dubreuil** [comment]
Ouin faque je ne sais pas pourquoi cette fonction me retourne `true` :/ J'espère que c'est une erreur de ma part, car sinon ce serait poche, puisque ça l'a impacté ma note du TP1.

J'utilises `flop.o` et `flop.h` de `https://github.com/guyfrancoeur/INF3135_H2020/raw/master/tp/tp2.zip`. J'assemble bien `flop.o` en  l'incluant dans la commande de compilation gcc de mon TP1. J'inclus bien `flop.h` en indiquant à gcc quel répertoire utiliser.

Je viens de rajouter les tests `!angle_incidence_marge_v1(0.0f, 0.26f)` et `!angle_incidence_marge_v1(0.0f, -0.26f)` et ils passent seulement pour `angle_incidence_marge_v1` comme cela devrait être (faire attention au `!`). @guyfrancoeur serait-il possible qu'il y ait un oubli dans cette fonction et donc que mes tests étaient trop exhaustifs?

**Comment by guyfrancoeur** [comment]
Allo,

Je vais tester avec tes valeurs dans qq minutes a suivre.

**Comment by benoit-dubreuil** [comment]
Hmmmm je viens de penser à quelque chose. Bien que les fonctions retourne `bool`, serait-ce possible que faire `angle_incidence_marge_v1` retourne autre chose que 0 ou 1? J'utilise la négation pour tester.

Je regarde ça.

**Comment by benoit-dubreuil** [comment]
Nope, les fonctions retournent `1` pour `angle_incidence_marge_v1(0.0f, 0.251f)`.

**Comment by cedricwtkUQAM** [comment]
C'est supposé retourner 1 justement

**Comment by benoit-dubreuil** [comment]
> Assert_true(angle_incidence_marge_v1(tesValeurs)) devrait retourner 0

Justement,

```
printf("%d\n", angle_incidence_marge_v1(0.0f, 0.250f));
printf("%d\n", angle_incidence_marge_v1(0.0f, 0.251f));
```

me retournent les deux 1 qui veut dire `true`.

**Comment by cedricwtkUQAM** [comment]
Je vais tester demain avec le nouveau flop file. Je te reviens avec asap

**Comment by guyfrancoeur** [comment]
Allo,

version 0.0.10009 semble corriger la précision de 0.001

Réagissez a ce post.

**Comment by benoit-dubreuil** [comment]
M. Guy Francoeur et moi avons passé pas mal de temps à déboguer pour essayer de trouver le problème. Il a trouvé le bug et l'a corrigé dans la nouvelle version du flop.o contenue dans tp2.zip.

Merci beaucoup tout le monde, surtout M. Francoeur! :)

**Comment by leopoldmaillard** [comment]
Bonjour,
C'est toujours la version 0.0.10008 qui est présente dans le tp2.zip
