### ISSUE TITLE
TP2 : Possibilité de données en entrée alterné?

### ISSUE THREAD

**Issue by MyriamOa** [guyfrancoeur/INF3135_H2020#129]
Bonjour, j'aimerais savoir si c'est possible d'avoir des transactions en entrée alterné?

Par exemple est ce qu'on peut avoir en entrée : 
1 01 0 //correction
125 02 A2 ERROR
145 03 G 0.0
12 02 A1 ERROR
145 03 D 0.0 
....
ou juste des données de meme transaction comme : 
146 03 D 1.0019
151 03 G 11.200
156 03 D 12.100

**Comment by guyfrancoeur** [comment]
Bonjour,

tout les codes de trx sont permis.

... exemples à venir.

**Comment by benoit-dubreuil** [comment]
> les `timestamp` doivent être chronologique.

Juste pour être sûr, les `timestamp` sont indépendant du type de transaction, i.e. pour 03 on est rendu à 143 par exemple et pour 02 il est impossible qu'il soit 34?

**Comment by jloga12** [comment]
> Bonjour,
> 
> Tous les codes de trx sont permis. (il n'y a pas d'ordre ou de groupe pour les types de transactions)
> 
> les `timestamp` doivent être chronologique.
> 
> Comme ceci:
> 
> ```
> 33 01 0 
> 125 02 A2 ERROR
> 145 03 G 0.0
**> 12 02 A1 ERROR //vous devez ignorer cette transaction (timestamp error)**
> 145 03 D 0.0
> ```
> 
> Merci pour la question.
> 
> Réagissez a ce post.

De ce que j'ai compris de sa réponse, c'est qu'on fait juste ignorer cette transaction car, en effet, elle n'est pas valide à cause qu'elle ne suit pas la chronologie.
