### ISSUE TITLE
TP2 : Nouveau requis pour le tp2

### ISSUE THREAD

**Issue by guyfrancoeur** [guyfrancoeur/INF3135_H2020#130]
Bonjour,

Dans le tp2 il existe un librairie. Cette librairie doit être à jour. Pour vous forcer à prendre la bonne il y a mainteanant un nouvelle fonction flop_version(...). Consultez le fichier `flop.h`

La premiere sortie dans `stdout` sera la version de la librairie exemple

identique (la ligne 1)
`0.0.1005` est variable 
```
version #: 0.0.10005
06 ... // après vous ajoutez la suite...
```

**Comment by LorenaMedina** [comment]
Pour la fonction flop_version(version_t *v), j'ai passé le pointeur, pourtant il n'a pas un affichage.
Est-ce qu'il y a quelque chose que je doit faire avant appeler la fonction?
Merci.

**Comment by Denowrrz** [comment]
Le role de la fonction n'est pas l'affichage.
