### ISSUE TITLE
TP2 Transaction 05, que dois-je prendre comme décision ?

### ISSUE THREAD

**Issue by kegosu** [guyfrancoeur/INF3135_H2020#131]
Bonjour, 
dans l'exemple du trx 05 on a ce qui suit 
183 05 19 911
185 05 19 0
191 05 15 1
198 05 16 2
199 05 15 0
le 16 2 n'a jamais été rétabli par un 16 0 à la fin alors que le 19 et 15 l'ont été donc est ce que le MCAS reste désactivé dans ce cas?
(il faut que tout les systèmes soit rétablis pour l'activer? )
merci

**Comment by Denowrrz** [comment]
Je cite : "MCAS sera réactivé lorsque **tous** les systèmes seront opérationnels; "

**Comment by guyfrancoeur** [comment]
Allo,

Voir énoncé : [ici](https://github.com/guyfrancoeur/INF3135_H2020/blob/master/tp/tp2-%C3%A9nonc%C3%A9.md#r%C3%B4le-de-votre-programme)
