### ISSUE TITLE
TP2: trx 01

### ISSUE THREAD

**Issue by LorenaMedina** [guyfrancoeur/INF3135_H2020#132]
+ Pour la ligne :
    **1979998 01 9**

On affiche une sortie?
Ou l'on passe à la suivante car l'état *9* n'est pas reconnu?

Merci

**Comment by cryptoswarm** [comment]
Si on considère que 9 est une valeur obtenue d'un capteur et vu qu'elle n'est pas acceptée donc on affiche un code 08. 
Sinon, je me demande comment est-ce possible qu'un état autre que celles de 0 à 4 soit parmi les valeur des transaction en entree.

**Comment by guyfrancoeur** [comment]
Réagissez aux posts svp.

**Comment by MoonscriB** [comment]
J'interprèterais moi aussi une valeur d'état ![0-4] comme se méritant un 08.  Je ne sais pas non plus comment une telle valeur pourrait être reçue mais justement : c'est notre défi de construire quelque chose de robuste face à certains aspects inconnus, n'est-ce pas ?  Et je crois que l'idée de output vers une boîte noire nous force à laisser un log qui soit le plus complet possible.

**Comment by MoonscriB** [comment]
Je reviens à cette question avec une nouvelle interrogation : 

On dit dans la question #114 que toute valeur incacceptable a pour effet de désactiver le MCAS.  Est-ce qu'une valeur inacceptable ici, pour la trx01, a pour effet de le désactiver en plus de générer un 08 ?  Je dirais que oui, même si je n'aime pas tellement cela, prenant ce qui suit à la lettre : 

>"Tant qu'il y a des erreurs l'avion doit rester dans les mains du pilot (humain)."
