### ISSUE TITLE
capteurs d'angle d'incidence A4

### ISSUE THREAD

**Issue by kegosu** [guyfrancoeur/INF3135_H2020#133]
Bonjour,
Comment faut-il gérer le cas du capteur A4 qui n'existe pas : 141 02 A4 10.5 //n'existe pas
on a seulement les cas où la valeur est inacceptable ou que celui-ci donne une erreur.
merci

**Comment by riadsm** [comment]
Il n'existe pas, pourquoi tu le gèrerais ? Tu n'as pas à le considérer, ignore-le. Les valeurs possibles d'angles sont A1 A2 et A3.

**Comment by guyfrancoeur** [comment]
Ceci est le cas appelé  `pure garbage` (données (ou bruits) sans aucune valeur)

Bravo @riadsm 

Réagissez aux posts.

**Comment by ahmadFara123** [comment]
Si on obtient des valeurs valide pour A1 et A2 , alors il y'aura aucune valeur pour A3 n'est ce pas ?
