### ISSUE TITLE
TP2: flop.h

### ISSUE THREAD

**Issue by krimo995** [guyfrancoeur/INF3135_H2020#134]
Bonjour @guyfrancoeur ,

J'aimerai attirer votre attention sur les fichiers flop.h et flop.o fourni dans le dossier tp2.zip en particulier sur la fonction **stabilisateur_horizontal_conforme_v3**. 

Dans mes tests produits dans tp1.c, dans l'un des tests traitant cette fonction j'ai introduit deux valeurs comportant 4 chiffres après la virgule et qui devraient être non valides à savoir 1,9001 et -1,9001. En testant avec les fichiers flop.h et flop.o fournis dans tp1.zip ces tests passent avec un assert_false et ne font pas tomber la fonction **stabilisateur_horizontal_conforme_v3** sauf que ce n'est pas le cas avec ceux fournis dans tp2.zip. Y aurait-il une erreur quelque-part ou on devrait dorénavant se limiter à deux chiffres après la virgule en ce qui concerne les tests.

Merci.

**Comment by guyfrancoeur** [comment]
Bonjour,

Dis moi si ceci est ok pour continuer

Je vais vérifier dans le tp1 nous étions plus gentil ou tollérant.  
Dans le tp2, nous devons considérer 3 décimales seulement.

Réagissez a ce posts

**Comment by krimo995** [comment]
Parfait on se tient à ça pour la suite, merci.
