### ISSUE TITLE
TP2, ANGLES. Incohérence d'une nouvelle contrainte

### ISSUE THREAD

**Issue by hydraslahir** [guyfrancoeur/INF3135_H2020#135]
### Une contrainte contradictoire a été ajoutée. 
Je suppose que ce n'est qu'une erreur inattention et qu'elle sera retirée.

![incohérence](https://user-images.githubusercontent.com/55253792/76664603-532b5700-655b-11ea-9c42-cbb6ce758dad.png)

**Comment by cedricwtkUQAM** [comment]
Elle est ou la contradiction?

**Comment by kegosu** [comment]
la val max pour l'angle c'est 360 degrés qui est logique et les autres spécifications que tu viens de mentionner en bas, c'est la différence entre deux angles de capteurs.

**Comment by hydraslahir** [comment]
# L'avion va crash les boyss
![plane_Crash](https://user-images.githubusercontent.com/55253792/76691686-d912d500-6623-11ea-87d2-8b0c8e8812ae.gif)

## Ce n'est pas une différence
**"Quote":** la tolérance entre les capteurs d'angle d'incidence doit être inférieur ou égale à 0.250.

**Définition de tolérance:** Limite de l'écart admis entre les caractéristiques réelles(delta) et les caractéristiques prévues(0.250).

* Même si [-29.5, -0.5] était une différence, c'est impossible d'avoir X et Y qui fonctionnent...
X - Y < 0
Y - X < 0
on arrive au résultat que X < Y et que X > Y, **impossible**

## L'angle n'est pas entre 0 et 360

Les angles **dépendent de l'état de l'avion**.
* Si l'avion est au TARMAC, les angles devraient être très bas et très peu variables (0 ± 0.2)
* Si l'avion décolle, son angle devrait être élevé, dans ce cas entre [2.5 et 51.0].
* Si tu descends, ton angle est négatif [-29.5, -0.5]

Tu ne peux pas descendre avec un angle positif... sauf si tu fais un loop à 180+ degrés
(ce qui est ma foi impressionnant), mais tu vas dans le sens opposé... et tu es à l'envers.

**Comment by guyfrancoeur** [comment]
Allo,

On ne lâche pas ca va bien. 😉

**Comment by LorenaMedina** [comment]
> Si l'angle est ( ± 360 ) 377.25 on peut dire qu'il est invalide sans autre vérification:
Ça veut dire, **ignorer la ligne** et qu'elle ne génère pas aucune sortie Trx ?

**Comment by hydraslahir** [comment]
# 360 est inutile(pour l'instant (\# TP3) )
La vérification [-360, 360] est inutile, tu as des méthodes qui valident la valeur d'angle anyway:
* decollage_angle_VX [2.5, 51.0]
* vol_angle_conforme_vX [-9, 9]
* ...

Même un angle de 90Deg aurait été invalide aussi, car la valeur minimale d'angle incidence est -29.5(ATTERRISAGE) et maximale de 51.0(DECOLLAGE).

toutes les méthodes de validation que tu possèdes vont **return false** avec un angle de 90Deg, 60Deg ou meme 52Deg

## Question
Pour ta question, ça veut simplement dire que tu sais à 100% que ya une erreur, elle devrait générer une TRX à un certain point.

## Conseil
Faites juste ignorer la ligne 
> 142 02 A1 377.29 //une erreur à gérer. les valeurs acceptées sont entre [ ± 0-360 ] degrés

**Comment by guyfrancoeur** [comment]
Bonjour,

Il ne faut pas ignorer la ligne le timestamp est bon.

Bien que nous savons que l'angle soit pas correct en fonction de l'état, ici nous avons une information additionnelle.  Le sensor produit une valeur qui avant même sa validation est jugée invalide ou erroné.

J'ai dit : `//une erreur à gérer. ...`
```
142 02 A1 377.29 //une erreur à gérer. les valeurs acceptées sont entre [ ± 0-360 ] degrés
```

Comment est-ce possible de fournir un conseil qui va complètement à l'opposé de cette directive ? 👎 

`ignorer` et `gérer` ne sont pas ÉGAL.  Attention 🛑 @hydraslahir  🛑 cette fois le conseil n'est pas le bon.

**Comment by hydraslahir** [comment]
J'avoue que l'interpretation est mauvaise, je voulais dire d'ignorer la ligne d'exemple, mais l'erreur est encore une erreur a gérer

**Comment by hydraslahir** [comment]
Voici mon point de vue,
Valider +/- 360Deg n'apporte aucun avantage au code.
Il serait facile de dire if(>360) quitte, mais ca va plus loin que ca. Il faut valider si le capteur appartient a A1, A2 ou A3(car un capteur A4 de 2500Deg ne nous affecte pas).

Ainsi, pour simplement vérifier 360, on ajoute 2 conditions(-360, +360) et 3 comparaisons et si c'est valide, on teste la valeur, valeur qui va être ENCORE testée pour sa valeur et son A1, A2 et A3.

Tester 360Deg ajoute 5 étapes supperflues(ou 2 si le code est optimal) pour tester un scénario unique qui ne se produira littéralement (presque) jamais. De plus, advenant qu'un tel scénario se présente, un code normal VA le rejetter de toute façon. 

Ça peut être plus rapide pour le scénario(AX 360+), mais c'est tout.
Sur 1'000'000 transaction AX, si une seule est A3 4000, on va avoir sauver environ 6 opérations, mais perdu 2'000'000 puisque tous les autres AX doivent passer cette vérification.

S'il y a un avantage à tester +/-360 que je n'ai pas vu, j'aimerais le savoir.
