### ISSUE TITLE
TP2: 02: Lecture d'un capteur d'angle d'incidence

### ISSUE THREAD

**Issue by LorenaMedina** [guyfrancoeur/INF3135_H2020#136]
Quand on reçoit:  124 02 A1 **5.5**
1. On evalue la **valeur inacceptable**, en fonction du état d'appareil.?
2. On evalue si possible erreur de **marge** vers les dernières lectures des autres capteurs?

**Comment by kegosu** [comment]
1- oui, c'est en fonction de l'état de l'appareil.
2- l'évaluation se fait suite à la lecture de 2 capteurs.

**Comment by lisacsn** [comment]
Si l'état a une valeur inacceptable comme dans l'énoncé ```1979998 01 9``` , comment devons-nous traiter la transaction 02? Devons-nous simplement comparer les capteurs 2 à 2, sans comparer l'angle d'incidence en fonction de l'état?

**Comment by benoit-dubreuil** [comment]
> Si l'état a une valeur inacceptable comme dans l'énoncé `1979998 01 9` , comment devons-nous traiter la transaction 02? Devons-nous simplement comparer les capteurs 2 à 2, sans comparer l'angle d'incidence en fonction de l'état?

Si une ligne fut fournie avec un état inacceptable, alors l'état est remis avec sa valeur par défaut. La valeur par défaut est une décision personnelle.

**Comment by RmannDev** [comment]
bonjour,
je lis l'énoncée et je ne vois null part des valeurs par défaut. 
Quelqu'un peut m'orienter s'il vous plait.

Merci.

**Comment by benoit-dubreuil** [comment]
> bonjour,
> je lis l'énoncée et je ne vois null part des valeurs par défaut.
> Quelqu'un peut m'orienter s'il vous plait.
> 
> Merci.

Ce n'est pas dans l'énoncé; c'est quelque chose qu'il fallait déduire, mais le prof en a heureusement parlé suite à des questions. Voir #160.

**Comment by RmannDev** [comment]
Mais déduire à partir de quoi ? quel passage de l'énoncé nous permet de déduire ces valeurs par défaut ? 
selon #160 : l'état par défaut est TARMAC et c'est tout ce que nous dit #160; qui nous parle aussi de valeur par défaut sans nous dire lesquelles. 
Questions ??
Est ce qu'on doit déduire ces valeurs en fonction de l'état par défaut ?? si oui comment ??

supposons que l'état de l'appareil est ETAT_VOL (L'appareil est en vol), et que nous recevons des données des capteurs qui ne sont pas acceptable alors on doit réinitialiser les capteurs avec les valeurs par défaut (lesquelles ???). comment ? en les remettant l'appareil a l'ETAT_TARMAC ?? je ne comprends pas ?????

**Comment by guyfrancoeur** [comment]
Allo,

C'est le rôle et une tâche du programmeur de prendre cette décision et d'établir les défauts.  

Tu dois faire certaines actions pour que ton programme marche.

Il faut gagner en autonomie.  TOUT N'EST PAS DIT OU SPÉCIFIÉ.
Tu dois tenter et faire des variables, faire des fonctions, faire des choses, prendre des décisions.

Je ne dis pas les noms de variables ou des fonctions ... NON.  Pourtant ça semble naturel d'en faire.

Même chose pour les défauts. Le défaut est une valeur avec laquelle tu vas travailler pour savoir si les choses ont bougé, changées.  Exemple une variable qui est égale a la valeur par défaut n'a surement pas changé.

@RmannDev ton posts n'est pas à la bonne place. -1 points

Garde une attitude professionnelle.
