### ISSUE TITLE
TP2: 03 Lecture de longueur d'un des volets

### ISSUE THREAD

**Issue by LorenaMedina** [guyfrancoeur/INF3135_H2020#137]
Pour la ligne:
161 03 D **-1.700**

La valeur -1.7 , est *inacceptable*,
- parce qu'on ne peut pas considérer le volet ouvert?
ou
- parce que qu'un longueur n'est pas négatif?

**Comment by kicak2009** [comment]
C'est pas mal plus pour la deuxième question, puisque la valeur ne peut pas être négative. 
Si c'est le cas, il y aurait un sérieux problème de mécanique!
