### ISSUE TITLE
TP2 : 02 Cas Marge

### ISSUE THREAD

**Issue by LorenaMedina** [guyfrancoeur/INF3135_H2020#138]
Pour la ligne 170, le cas de marge est évalué avec la ligne 156,
car pour 161 la valeur était inacceptable, n'est pas?

**156 03 D 12.100**
161 03 D -1.700
167 03 G ERROR
**170 03 G 10.000**

**Comment by guyfrancoeur** [comment]
Bonjour,

Dans ce cas,

- la ligne au temps 161 écrase la valeur du temps 156 non ? OUI.
- Si la ligne au temps 161 est inacceptable alors nous n'avons pas de valeur STABLE ou UTILISABLE.
- Donc nous n'avons pas encore de valeur UTILISABLE pour le sensor `D`.
- Donc au temps 170 il n'y a pas encore tout ce qu'il faut pour prendre une décision.

Êtes-vous d'accord avec le raisonnement ?

Merci pour la question et le cas.

Réagissez à ce post.

**Comment by LorenaMedina** [comment]
Je m'explique, on a dans l’énoncé en réponse de la ligne 170  :  
**06 11 170 MARGE**
Donc je veux savoir le raisonnement.
Merci

**Comment by guyfrancoeur** [comment]
Allo,

il y a donc une erreur dans enoncé je vais révisé l'enoncé et corriger ca.
Il me semble que c'est un ajout donc possible.

Merci!

**Comment by LorenaMedina** [comment]
alors, pour confirmer, après les cas pour inacceptables pour **valeur** ou pour **marge** d'un sensor, on n'a pas une valeur utilisable pour comparer **la marge** des nouveaux valeurs arrivants pour ce sensor?

**Comment by kegosu** [comment]
156 03 D 12.100
161 03 D -1.700
si on a une valeur inacceptable pour le -1.700, faudrais pas la skip à la place et non remplacer cette valeur erroné par celle de 12.100?
merci

**Comment by kegosu** [comment]
156 03 D 12.100
161 03 D -1.700
est ce qu'il ne faudrais pas d'abord valider si la valeur -1.700 est acceptable pour la longueur du volet?
et si elle est erroné, faut-il pas la skip au lieu de remplacer cette valeur par celle valide en haut?
merci

**Comment by guyfrancoeur** [comment]
Bonjour,



> > `LM` alors, pour confirmer, après les cas pour inacceptables pour valeur ou pour marge 
> > d'un sensor, on n'a pas une valeur utilisable pour comparer la marge des nouveaux
> > valeurs arrivants pour ce sensor?

Si la valeur n'est pas valide (acceptable) nous ne pouvons pas basé notre décision sur celle-ci.

```
161 03 D -1.700
```
n'est pas acceptable ni valide.

DONC, est-ce que le sensor est maintenant brisé depuis le temps 161 ?  Les valeurs avant 161 ne sont plus considéré, vous êtes d'accord avec cela ?

> > `K` est ce qu'il ne faudrais pas d'abord valider si la valeur -1.700 est acceptable pour la longueur du volet?

OUI.

Si le sensor est en erreur (fourni par une valeur invalide) donc nous n'avons pas de valeur acceptable.  Traitez ceci comme vous pouvez.

Réagissez à ce post. (aux posts) obligatoire.

**Comment by MyriamOa** [comment]
Bonsoir,
j'ai cru comprendre que la dernière valeur de l'angle D lue et valide avant celle inacceptable sera celle qu'on va comparé avec la première valeur de l'angle G lue et valide? de par votre réponse précédente c'est comme ci dès qu'on lit une valeur d'un angle D ou G inacceptable avant une quelconque comparaison on n'oublie les anciennes valeurs valides lue ?

**Comment by lisacsn** [comment]
Si la dernière valeur de D est inacceptable, même s'il y avait une valeur acceptable avant celle-ci, elle va entraîner une erreur et on ne pourra plus prendre en compte de valeur pour D.

**Comment by cryptoswarm** [comment]
il faut utiliser le timestamp, les valeurs reçu du capteur gauche avant celle du capteur droite. 
après verification de la validité des valeur on peut procéder au calcul de la marge.

**Comment by thomasgericot** [comment]
Si je resume, si on a:
156 03 D 12.100
161 03 D -1.700
167 03 G ERROR
170 03 G 10.000
alors on ne peut rien faire puisque le volet D n'a toujours pas de valeurs valide( la valeur valide du temps 156 ayant ete mis a mal par cellle du temps 161).
SI a la suite on a 
171 03 D 20,
alors la on peut considerer que la marge n'est pas respecte (puisque 20 est une valeur possible pour le volet D)
Le raisonnement est-il correct ?
Merci pour votre reponse, excellente journee,
