### ISSUE TITLE
Question pour les sorties

### ISSUE THREAD

**Issue by kegosu** [guyfrancoeur/INF3135_H2020#140]
Est ce que les sorties seront stocké dans un fichier de sortie ou seront juste afficher à la console?
car les entrées et sorties seront mixées à la console ou est ce qu'on garde chaque sorties et on les affichent ensemble ordonnées à la fin?
merci

**Comment by LorenaMedina** [comment]
L'énoncé dit:
Dans certains cas vous avez à produire des données sur le canal standard. Ceci simule le dialogue (les données) des boîtes noires de l'avion.

**Comment by alancipher** [comment]
selon moi il faut traiter les données entrées par stdin et puis juste afficher celles qui nécessitent ou exigent  des messages de sortie sur notre sortie standard stdout

**Comment by JonPhno** [comment]
Je crois que notre programme doit prendre des transactions en entré et selon l'état des système et les valeurs acceptable, doit produire une sortie. Pour ce qui doit être affiché, l'énoncé couvre cela. Tout doit être envoyé vers la sortie standard.

**Comment by guyfrancoeur** [comment]
Bonjour,

Votre programme accepte les données sur le canal `stdin`, et produira lorsque nécessaire les échanges sur le canal `stdout`.
