### ISSUE TITLE
Format de sortie 

### ISSUE THREAD

**Issue by YounesJulien** [guyfrancoeur/INF3135_H2020#141]
D'après les informations fournis dans la donnée, on connais le format de l'entrée du programme grâce à des exemples donnée.

Je n'arrive pas à comprendre de quel manière la sortie doit être écrite. 

Si j'interprète mal une partie de la donnée faite le moi savoir s'il vous plaît ! 

Merci d'avance.

**Comment by ArielleSadeu** [comment]
Les spécifications concernant le format des sorties sont données dans la partie " voir les cas et les traitements " de l'énoncé . 

En fonction de l'état du système , les valeurs inacceptables.... Tu dois produire une sortie lorsque nécessaire. Pour chaque entrée tu as un format de sortie dans la partie "Transaction en sortie", suivi d'exemples.

Par exemple l'entrée cas trx 03: timestamp = 161 (capteur donne une valeur inacceptable),  génère un code de trx 08 (sortie).
Le format de sortie est : 
08 <sensor> <timestamp> [information additionnelle]

**Comment by ArielleSadeu** [comment]
Le format de sortie est plutôt celui-ci , tel que mentionné dans l'énoncé:

08 <sensor> <timestamp> [information additionnelle]
