### ISSUE TITLE
Etat système

### ISSUE THREAD

**Issue by kegosu** [guyfrancoeur/INF3135_H2020#142]
Si l'état du système est brisé et qu'il est pas réparé  : 
1929999 01 4
1979998 01 9
comme ici le 9 est en erreur et que les trx 2 à 4 s'en viennent après , que faut-il faire vu que tout dépend de l'état du système du trx1 ?
merci

**Comment by kicak2009** [comment]
D'après moi, c'est la dernière donnée valide qui doit être utilisée. Par exemple :
1929999 01 4   <- État valide
1979998 01 9   <- État non valide, donc l'état est encore 4.

**Comment by LorenaMedina** [comment]
La deuxième ligne a du écraser la valeur de la première, donc on n'a pas un état,
D'après les explications du issue #138 .

**Comment by kegosu** [comment]
ouais , je me suis dis aussi. Du coups , il y a un gros problème ici vu que tout dépend d'une valeur correcte de l'état...

**Comment by guyfrancoeur** [comment]
Bonjour,

Je ne comprend pas en quoi ceci est un problème ? Tant pour le programme (exécution) ou le programmeur.

De plus, ce cas est très improbable.  C'est le pilot qui manipule l'état de l'avion...

Enfin faites ce que vous voulez.  J'en ai surement assez dit.

**Comment by LorenaMedina** [comment]
À titre d'exemple, je presume le probable problème est si on aurait ces 3 lignes de time, 
   la ligne 2 écrase le bon état **2**.
   À la ligne 3, on n'a pas état pour évaluer la valeur de l'angle.
   Mais je comprends ce cas est très improbable.
   1 01 2
   2 01 9
   3 02 A1 5.5
Merci

**Comment by stephanie-moreau** [comment]
Je crois qu'il serait préférable de fermer le MCAS. Si je me fie à l'énoncé pour la transaction 08, nous avons

08: Détection d'une valeur inacceptable provenant de senseurs
 + ```08 <sensor> <timestamp> [information additionnelle]```
 + ```08 <VOLET=11|SH|AI|ETAT> <size_t> [D|G|valeur]```

où je crois qu'ETAT fais référence à l'état de l'appareil. Ainsi, si le sensor de l'état de l'appareil envoie une valeur inacceptable pour un système dont les valeurs doivent être gérées, le MCAS devrait devenir inactif.
