### ISSUE TITLE
TP2 : Lancement du programme sans pipe

### ISSUE THREAD

**Issue by MoonscriB** [guyfrancoeur/INF3135_H2020#143]
Bonjour,

quelque chose me laisse perplexe : la possibilité de démarrer le programme avec un simple 
>$ ./tp2

Est-ce que cela veut dire que l'on doit gérer l'entrée interactive de transactions au terminal _pendant_ que le programme fonctionne ?  Je ne vois pas d'autre façon de les obtenir dans ce cas précis.

**Comment by MyriamOa** [comment]
Salut
c'est exactement ton idée que j'ai aussi, lorsqu'on entre juste ./tp2 cela signifie que tu vas passer les données toi meme à ton programme via le terminal.

**Comment by RmannDev** [comment]
Salut,
je me posais aussi la même question que vous et je pense que oui vous avez vu juste sauf avis contraire. Je pense que Oui, parce qu'il a écris dans le sujet : _" Dans certains cas vous avez à produire des données sur le canal standard. Ceci simule le dialogue (les données) des boîtes noires de l'avion. Le résultat en sortie est celui qui sera évalué."_

**Comment by cedricwtkUQAM** [comment]
> Bonjour,
> 
> quelque chose me laisse perplexe : la possibilité de démarrer le programme avec un simple
> 
> > $ ./tp2
> 
> Est-ce que cela veut dire que l'on doit gérer l'entrée interactive de transactions au terminal _pendant_ que le programme fonctionne ? Je ne vois pas d'autre façon de les obtenir dans ce cas précis.

En effet, de ce que j'ai compris de l'experience du TP1 c'est que ton programme doit fonctionner dans tous les cas possibles. 
Dans cette situation, en fournissant les resultat d'un roulement de script, d'un fichier texte, d'entrees manuelles etc. Donc oui, il n'a pas été laissé au hasard que le programme puisse s'exécuter ainsi.

**Comment by AlexandreBillereau** [comment]
Je voudrais être sur de comprendre votre logique, quand on lance ./tp2 le programme devrais nous inviter par la suite a entrée ligne par ligne les données a la main?

De plus pour chaque ligne entrée on écrit la sorti diréctement avant la prochaine ligne qu'on devra rentré? ce qui pourais donner par exemple : 

161 03 D -1.700  //valeur innaceptable 
08 11 161 D        //sortie d'erreur
09 MCAS off       //mcas off directement après une erreur
162 05 19 911    //erreur système
06 19 183           //sortie d'erreur

Dans les autres cas avec un pipe. Il y aurais une lecture simple et une sorti apres par exemple

Entré : 
161 03 D -1.700  //valeur innaceptable 
162 05 19 911    //erreur système

Sortie : 
08 11 161 D        //sortie d'erreur
09 MCAS off       //mcas off directement après une erreur
06 19 183           //sortie d'erreur

ai-je bien compris ?

**Comment by cryptoswarm** [comment]
162 05 19 911 //erreur système
06 19 183 //sortie d'erreur   devrait être  06 19 162

**Comment by AlexandreBillereau** [comment]
@cryptoswarm Merci haha, je vais corriger. 
Mais d'après toi ai-je bien compris le lancement du programme sans pipe ?

@MoonscriB @MyriamOa je vous tag pour avoir potentiellement une réponse aussi de votre part, 
Merci d'avance.

**Comment by MoonscriB** [comment]
Bonjour,

je n'irais pas jusqu'à avancer que le programme doit "nous inviter" à entrer des transactions.  Il est après tout conçu - théoriquement - pour recevoir des données de capteurs et d'autres systèmes, et non pas pour être lancé d'un terminal.  Que le programme puisse recevoir les transactions en ligne de commande, séparées par des sauts de ligne, me semble suffisant.  C'est mon opinion.

**Comment by AlexandreBillereau** [comment]
@MoonscriB Je suis pas sur de bien comprendre alors, pourais tu me donner un exemple du comportement du programme quand on le call sans pipe et ce qu'il est sensé faire ?

**Comment by MoonscriB** [comment]
@AlexandreBillereau Je ne sais pas quoi rajouter sans donner des détails d'implémentation... désolé.
