### ISSUE TITLE
TP2 : Arrêt du MCAS lorsque nous avons `ERROR` 3X consécutives ?

### ISSUE THREAD

**Issue by AlexandreBillereau** [guyfrancoeur/INF3135_H2020#144]
Bonjour à tous,

Lundi dernier en cour. Nous avons discuté que le MCAS devait être stopé, (dans le cas des erreurs en entrées), dans le cas de trois erreurs consécutives mais il n'y a pas d'indication. Cela aurait t'il changer ? 
La gestion ce fait même ci les erreurs ne sont pas "consecutive"?

Merci

- il y a résumer a la fin pour éviter de tout lire

**Comment by julienbigras1** [comment]
D'après ce que j'ai compris, la détection de 3 valeurs "ERROR" pour un même capteur doit être consécutive pour envoyer un transaction de sortie 06 qui indique qu'un système est en erreur. Par la suite, comme un système est en erreur, on peut mettre le système MCAS à off et afficher une transaction de sortie 09 (MCAS OFF).

**Comment by AlexandreBillereau** [comment]
ok ok donc ca me fait penser à une deuxième question. On est d'accord que MCAS est arreté seulement après une sortie 06 qui veux dire érreur d'un système. Une sorti 08 veux juste dire une valleur innaceptable et donc d'après l'énoncer pas besois de mettre le MCAS Off si c'est une sortie 08 ? Ai-je bien compris ? Si il faut la reposer en issue je le ferrais merci d'avence

**Comment by julienbigras1** [comment]
D'après l'exemple de l'énoncé, on dirait pas besoin de mettre le MCAS OFF après une erreur:
08 11 161 D
06 11 172 MARGE
06 12 179 3X
09 MCAS OFF

Il ne le met pas directement après la détection de l'erreur au temps 161 (affichage code 08). Mais je trouve qui serait logique de mettre le MCAS à off si trop de valeur inacceptable pour un capteur? Je n'ai pas vu dans l'énoncé un endroit où il mentionne cela.

**Comment by cryptoswarm** [comment]
Bonsoir,
Une question similaire a été déjà posée.
[https://github.com/guyfrancoeur/INF3135_H2020/issues/114](url)
Si je comprends bien, un capteur qui donne une valeur inacceptable doit être considéré comme si le system est en erreur puis on met le MCAS OFF. 

@guyfrancoeur  pouvez vous confirmer si le MCAS doit être désactivé dans le cas où un capteur donne une valeur inacceptable ?

**Comment by AlexandreBillereau** [comment]
@julienbigras1 moi aussi je serais d'avis de desactiver le MCAS directement après une sortie 06, car si les erreurs continuent d'aflluer au moins le MCAS sera Off. 

@guyfrancoeur Donc en plus de confirmer le question de @cryptoswarm, pouvez vous nous dire si il ne serais pas mieux de mettre le Mcas off directement après une sorti 06 

par exemple   

08 11 161 D
06 11 172 MARGE
09 MCAS OFF
06 12 179 3X

plus dans cette ordre

Merci d'avance

**Comment by guyfrancoeur** [comment]
Bonjour,

Est-ce que tout le monde a fait `09 MCAS OFF` dans le cas de détection (d'anomalies) ?

👍 pour oui
👎 pour non

**Comment by AlexandreBillereau** [comment]
@guyfrancoeur pour être sur vous parlez de valleur inacceptable quand vous dite "anomalies"? vous parlez pas d'erreur système!

**Comment by hydraslahir** [comment]
Tout dépend de ce que tu entends par anomalie;

* Ce sont des anomalies qui ne génèrent rien:
    + -1 2 A1 0.2 //timestamp invalide, mais non géré
    + 100 3 RT 3 //RT != (G ou D), non géré, ca pourrait être un capteur ailleurs dans un avion
    + //ligne invalide, mais ignorée

* Si par anomalie tu entends une **valeur inacceptable**, le MCAS s'éteint puisque le systeme n'est pas dans un état valide après une valeur inacceptable
    + 23 4 D chat // 08 12 ET 09 MCAS OFF
    + 176 3 G -2 // 08 11 ET 09 MCAS OFF

* Anomalie de systeme,
    + 34 5 12 -3  -->  06 ET MCAS OFF

* ERROR 3x
    + 06 ... 3X  ET MCAS OFF

* MARGE
    + 06 ... MARGE ET MCAS OFF

Le MCAS devrait fermer dans la majorité des anomalies, sauf celles de lignes invalides

**Comment by AlexandreBillereau** [comment]
Ok parfait merci @hydraslahir !
Donc pour resumer l'issue :

1 - Le Mcas sera off quand trois erreurs "Consecutive" sur le même capteur, donc on laisse bien deux chance à un capteur avant de mettre le MCAS Off. 

2 - Le MCAS devrait fermer (Off) dans la majorité des anomalies "soit erreur système et valleur innaceptable et entré 05", sauf celles de lignes invalides comme un timeStamp négatif ou une ligne inconnue.

**Comment by hydraslahir** [comment]
Grossièrement, c'est ce qu'il me semble. 
En passant, vous devriez vous assurer que les lignes suivantes ne font pas des erreurs de segmentation ( juste comme ca, car c'est plutôt fréquent )
* 13(\n)
* 13 (espace) (espace)
* 13 2 (espace)
* Incessunt inligato moventem inligato ordinatus finitimis hostiliter quae optimatum si vi quadam locum a aliquotiens Isauriam nomine subita optimatum eum quadam sollicite quae iuvant numero bellis finitimis inligato nomine aliquotiens si saepe iuvant arma numero Mesopotamiam repellenteque repellenteque arma bellis Persarum Isauriam repellenteque si e moventem finitimis eum ferocissimas rege vi in suis et vi copia arma in incessunt nostra conlimitiis perrupturus finitimis iuvant iuvant incursare usquam Isauriam adducta saepe gentes incursare Isauriam optimatum Mesopotamiam copia incursare ferocissimas eum iuvant repellenteque per optimatum rege incessunt gentes inligato copia bellis dederit in repperisset vi nostra Persarum locum saepe Persarum numero repellenteque.
