### ISSUE TITLE
TP2 : cas trx 02 - Erreur des angles

### ISSUE THREAD

**Issue by kicak2009** [guyfrancoeur/INF3135_H2020#145]
Bonjour,

Si la valeur d'un angle d'incidence ne fait pas parti dans les intervalles selon l'état de l'avion, ce serait quoi comme d'erreur? Par exemple :

```
99 01 0
...
124 02 A1 5.5
125 02 A2 5.6
```
Comme les intervalles des angles d'incidences doivent être entre -0.2 à 0.2 à cause de l'état 0, les lignes 124 et 125 sont à l'extérieur des intervalles voulus. Ce serait quoi comme message d'erreur? 

Comme ceci?
Output : 
```
08 13 124 5.5
08 13 125 5.6
```

Merci.

**Comment by guyfrancoeur** [comment]
Allo,

Ce n'est pas uniquement 09 MCAS OFF ?

dis-moi si ceci fait du sens.

GF

**Comment by kicak2009** [comment]
Donc, si je comprends bien :
```
99 01 0
...
124 02 A1 5.5
125 02 A2 5.6
...
150 02 A1 0.0
151 02 A2 0.05
```
Output : 
```
09 MCAS OFF
...
09 MCAS ON
```
MCAS revient à ON si les nouvelles valeurs sont valides?

**Comment by cedricwtkUQAM** [comment]
> Donc, si je comprends bien :
> 
> ```
> 99 01 0
> ...
> 124 02 A1 5.5
> 125 02 A2 5.6
> ...
> 150 02 A1 0.0
> 151 02 A2 0.05
> ```
> 
> Output :
> 
> ```
> 09 MCAS OFF
> ...
> 09 MCAS ON
> ```
> 
> MCAS revient à ON si les nouvelles valeurs sont valides?

Pas seulement si les nouvelles valeurs sont valides. MCAS revient a ON si **_tous_** les systemes seront opperationels.

**Comment by lisacsn** [comment]
On est d'accord que selon l'énoncé ```MCAS n'est pas actif lorsque les volets sont ouverts```, il faut opérer de la même manière pour la transaction 03 avec ```volet_ouvert_vX```
