### ISSUE TITLE
TP2: Question: Mention ERROR capteurs

### ISSUE THREAD

**Issue by cedricwtkUQAM** [guyfrancoeur/INF3135_H2020#146]
Est ce que tout type de transaction peut presenter la mention ERROR?
A titre d'exemple: trx: 01 peut il avoir une mention ERROR? 

Etant donné que les changements d'états ne prennent qu'une valeur, on peut penser que la seule option possible serait qu'il y a une **valeur inacceptable**. 

Mais ma question est plus dans l'aspect ou l'on **ne laisse rien au hasard**.

**Comment by guyfrancoeur** [comment]
Allo,

Es-tu capable de gérer le cas avec ce que tu sais ?

**Comment by cedricwtkUQAM** [comment]
Oui je devrait etre capable de gérer 😅
