### ISSUE TITLE
TP2 : trx 03 - MCAS OFF quand les volets ouverts

### ISSUE THREAD

**Issue by lisacsn** [guyfrancoeur/INF3135_H2020#147]
Bonjour,

Dans l'énoncé on peut lire : ```MCAS n'est pas actif lorsque les volets sont ouverts```.
Donc nous devons utiliser ```volet_ouvert_vX``` et vérifier que les volets soient fermés sinon le MCAS devient OFF si j'ai bien compris?

Or dans l'énoncé on peut aussi lire : 
```151 03 G 11.200```
```156 03 D 12.100```

Mais ne renvoie pas 09 MCAS OFF alors que l'énonçé du TP1 dit que "la borne inférieure afin de considérer les volets ouverts (incluse) est 0.9". Donc 151 et 156 devraient être des volets ouverts et devraient renvoyés MCAS OFF ? 

Je ne comprend pas pourquoi ce n'est pas le cas dans l'exemple de l'énoncé.

**Comment by julienbigras1** [comment]
D'après ce que j'ai compris de l'énoncé, je dirais que oui, il faut mettre le MCAS à OFF lorsque les volets sont ouvert. Je crois que 151 et 156 sont effectivement des cas où les volets sont ouvert, mais on ne voit pas le message MCAS OFF, car il est dans les ...  avec peut-être un MCAS ON.
Dans ce cas, fonctionne.

**Comment by cedricwtkUQAM** [comment]
Aussi lorsque l'enoncé dit: "Les volets".
Comment devons nous le comprendre? 
1) G : ouvert, D: ouvert -> MCAS OFF
2) G ou D: ouvert, D ou G: ferme -> MCAS OFF
