### ISSUE TITLE
Date de remise TP2

### ISSUE THREAD

**Issue by phsoucy** [guyfrancoeur/INF3135_H2020#149]
Bonsoir Monsieur @guyfrancoeur,

J'ai vu votre message #139 pulié le 15 mars nous demandant de finir le TP dans les temps.

Je vous demande de reporter la date de remise du TP2. La situation actuelle ne nous permet pas d'étudier convenablement. Je m'explique. J'ai des ami.es dans le besoin, qui n'ont plus d'emploi et qui n'ont plus assez d'argent pour faire leur épicerie. Les services communautaires cherchent des bénévoles puisque les besoins de la population augmentent considérablement. Je suis moi-même travailleur de la santé et on m'appelle pour rentrer travailler et je dois refuser parce que je dois travailler sur ce TP alors que le réseau de la santé ont besoin de main d'oeuvre de façon urgente...

Pouvez-vous svp essayez de comprendre davantage notre situation et reporter la date de remise devant le flou dans lequel on est en ce moment. Cela nous permetterait de souffler un peu et de réduire notre stress (prenons en considération que plusieurs sont dans des situations plus précaires que d'autres, par exemple les parents étudiants qui vivent une situation assez complexe).

Nous vivons une situation exceptionnelle où les études ne sont plus nécessairement une priorité à l'échelle de la vie sociale. Un peu plus d'écoute nous ferait du bien.

Merci.

**Comment by cedricwtkUQAM** [comment]
Je travaille aussi dans le domaine de la santé et je comprends que la situation est un peu exceptionelle. 
Je veux cloturer la session comme tout le monde alors je travaille sur le projet comme demandé mais étant donné les circonstances je suis daccord avec @phsoucy car nos emplois sont en jeux si l'on refuse de se présenter dans ces temps difficiles. Je supporte la demande de mon collègue et je vous prie monsieur de nous permettre quelques jours en plus. 

Cordialement,

**Comment by djamz47** [comment]
@guyfrancoeur Si je réponds à ce issue ai-je le droit à mon point d'intervention ?

Blague à part, je pense aussi qu'il serait pertinent de repousser compte tenu de la situation et du fait que beaucoup d'étudiants (moi y comprit) ne sont pas dans un environnement idéal pour effectuer des travaux assez longs / pas évidents de la maison.

Nous sommes malheureusement toujours dans l'inconnu quant à la remise des travaux pour le BAC en info à l'UQAM et c'est vraiment très désaggréable, mais pour info, les travaux d'autres cours ont été repoussés, ainsi que ceux des autres universités. C'est une situation désagréable pour tout le monde de devoir rester à la maison pour faire ses travaux.

J'aurai simplement "like" comme les 44 autres édutiants, mais je pense qu'il est mieux de mettre ça en mots pour supporter les 2 commentaires ci-dessus.

Merci.

**Comment by phsoucy** [comment]
J'ai eu l'info que le moratoire sur la remise des travaux sera étendu au 27 mars. Cela reste par contre à être entériné par le CA de demain. Nous aurons l'information par info direction au cours de la journée de demain.

**Comment by guyfrancoeur** [comment]
Bonjour,

Merci @phsoucy, pour tes démarches.

Le moratoire sauf erreur concerne ne concerne en rien la remise des travaux du premier cycle.

> > Nous vous rappelons que dans le contexte de la COVID-19, les activités académiques sont suspendues à l’UQAM jusqu’au 27 mars 2020 inclusivement. Les activités de recherche et de création sur les campus, dans les laboratoires ainsi que les activités de terrain sont également suspendues.

Pour nous il n'y a aucun impact, car nous faisons tout par github. Plus encore en informatique.

Par contre, je vais permettre à ceux qui le veulent de continuer le supplice et le développement encore quelques jours.
Donc, la date de remise sera, repoussée. Voir énoncé.

À bientôt.

G

**Comment by kicak2009** [comment]
Bonjour @guyfrancoeur,

J'ai relu l'énoncé, mais j'aimerais savoir si j'ai bien compris : 
```
version #: 0.0.10004
...
09 MCAS OFF     //off à cause de qqc je ne sais pas quoi, ce n'est pas dit dans l'exemple!
...
09 MCAS ON
08 13 142 A1
...
08 11 161 D
06 11 172 MARGE //ajouter par la suite
09 MCAS OFF     //ajouter par la suite
06 12 179 3X
09 MCAS OFF
06 19 183
09 MCAS OFF
07 19 185
...
```
En mettons à la ligne « 06 11 172 MARGE », il déclenche le message « 09 MCAS OFF ». Ma question, si MCAS n'est pas revenu à ON, on continue à afficher MCAS OFF comme après « 06 12 179 3X »? 

Je veux être certain parce que j'ai configuré pour que ça affiche une fois MCAS OFF tant et aussi longtemps que c'est pas revenu à ON, peu importe d'autres erreurs. Par exemple : 
```
...
08 11 161 D
06 11 172 MARGE
09 MCAS OFF    
06 12 179 3X  <-- Affiche l'erreur, mais MCAS est déjà à OFF.
06 19 183  <-- Affiche l'erreur, mais MCAS est déjà à OFF.
07 19 185
09 MCAS ON
...
```
Ou bien : 
```
...
08 11 161 D
06 11 172 MARGE
09 MCAS OFF    
06 12 179 3X  <-- Affiche l'erreur, mais MCAS est déjà à OFF.
09 MCAS ON  <-- L'erreur de l'état 12 est rétabli.
06 19 183
09 MCAS OFF
07 19 185
09 MCAS ON
...
```
Merci.

**Comment by guyfrancoeur** [comment]
Bonjour,

Tu aurais du créer un nouveau post. 😢 Tu es hors sujet dans ce fil de discussion.

09 MCAS OFF à chaque fois.
