### ISSUE TITLE
TP2: Question: état du système (ou des systèmes) au démarrage ?

### ISSUE THREAD

**Issue by cedricwtkUQAM** [guyfrancoeur/INF3135_H2020#150]
Au demarrage de notre programme, devons nous supposer que tous nos systemes sont operationnels ou non operationels?

**Comment by AlexandreBillereau** [comment]
j'imagine que quand l'avion décole les systèmes sont oppérationelle ! donc le MCAS et ON jusqu'a l'arriver d'une erreur

**Comment by cedricwtkUQAM** [comment]
![image](https://user-images.githubusercontent.com/55606236/77125057-1065f500-6a1b-11ea-887e-f8f68441e96d.png)
Si tous les systemes sont operationels au debut du programme le MCAS devrait etre ON. Or a la premiere ligne il est OFF. Est ce que ca implique les volets qui sont ouverts? Tellement d'ambiguite dans ce travail :(

**Comment by Marie287** [comment]
Je pense que la première ligne fait référence à une erreur et non à l'état du MCAS au moment du décollage.
Cet exemple veut juste dire qu'une anomalie a désactivé le MCAS, et que dans ce cas-ci, il s'agit de la première erreur.
Il y a en effet certaines anomalies qui ne produisent aucun autre message d'erreur mis à part la désactivation du MCAS.

Mais de toute façon, au décollage le MCAS était actif.

**Comment by AlexandreBillereau** [comment]
Nan en vrai il a pas tord !! vu que le programme ce lance en affichant la version le MCAS a bien l'air off au début. À deux jour de la remise je dirais que le Mcas est off au final et que au debut il attend de voir si tout les systèmes son bon. 

Mieux vaux se fier au comportement du programme donner en exemple.

**Comment by leopoldmaillard** [comment]
Dans sont état actuel le sujet laisse place à plusieurs interprétations possibles en effet, et il ne semble pas forcément y avoir de « bonne » réponse...

De même, @cedricwtkUQAM, sur ton image, je me demande pourquoi le MCAS ne se désactive qu’après l’erreur 06 12 179 3X mais pas directement après l’erreur 06 11 179 MARGE... Puisque l’erreur d’un seul système devrait entraîner la désactivation du MCAS.

**Comment by stephanie-moreau** [comment]
Sans parler d'erreur nécessairement, peut-être qu'à partir de la première transaction lu il était possible de déduire que les volets étaient ouverts, ce qui a eu pour effet d'éteindre le MCAS. Cela pourrait faire du sens comme il n'y a pas nécessairement de message, autre que la transaction 9, lorsque les volets sont ouverts.

**Comment by hydraslahir** [comment]
@Marie287 a bien résumé.

Le systeme est ON jusqu'à preuve du contraire. 
> MCAS doit être désactivé lorsqu'un système est en erreur.

**Pas d'erreur, pas de OFF.**

C'est ce que je pense; mais ça devrait être spécifié dans l'énnoncé ^..^

**Comment by MaximCrudu** [comment]
https://www.ac-montpellier.fr/cid119327/sortie-des-volets-pour-le-decollage.html

**Comment by cedricwtkUQAM** [comment]
> Dans sont état actuel le sujet laisse place à plusieurs interprétations possibles en effet, et il ne semble pas forcément y avoir de « bonne » réponse...
> 
> De même, @cedricwtkUQAM, sur ton image, je me demande pourquoi le MCAS ne se désactive qu’après l’erreur 06 12 179 3X mais pas directement après l’erreur 06 11 179 MARGE... Puisque l’erreur d’un seul système devrait entraîner la désactivation du MCAS.

Je ne sais pas, c'est l'image de l'enoncé, il en reste du travail. 

Ne rien laisser au hasard dans un ensemble de taches floues c'est pas facile.

**Comment by AlexandreBillereau** [comment]
@cedricwtkUQAM En vrai comme @leopoldmaillard  a dit, il n'y a pas de bonne réponse.

Donc tout le monde n'aura pas la même sortie de programme. Ce qui compte c'est que le MCAS soit désactivé quand il faut, ou au moins aux moments critiques.

Donc qu'il soit désactivé au début et activé après une fonction qui vérifie si t'es systèmes son tous "opérationnel" ou alors activé dès le début le MCAS. Au final cela ne change rien

**Comment by hydraslahir** [comment]
Tu ne peux pas tester si tes systemes sont opérationnels si tes systèmes ne t'ont pas envoyé l'information au préalable. Tu n'auras pas nécessairement de l'information sur les systèmes 11 à 19 et attendre d'avoir une information '0' sur ces 8 systèmes peut prendre beaucoup de temps, surtout s'ils n'envoient pas souvent d'information.

**Comment by guyfrancoeur** [comment]
Allo,

Point bonus pour @MaximCrudu [ici](https://github.com/guyfrancoeur/INF3135_H2020/issues/150#issuecomment-601479024) @hydraslahir [ici](https://github.com/guyfrancoeur/INF3135_H2020/issues/150#issuecomment-601478763) BRAVO.
Bravo aussi à @stephanie-moreau [ici](https://github.com/guyfrancoeur/INF3135_H2020/issues/150#issuecomment-601475596)

Merci a vous pour vos raisonnement et votre logique.
