### ISSUE TITLE
TP2: Error à la transaction 01?

### ISSUE THREAD

**Issue by Eben99** [guyfrancoeur/INF3135_H2020#151]
Est-ce qu'il est possible d'avoir la donnée ERROR en transaction 01? par exemple:
```
122 01 0
130 01 ERROR
145 01 9
        
```
Et donc de facto on doit lever une transaction 06?

**Comment by ricardoDeMedeiros** [comment]
Je ne pense pas que tu puisses avoir une donnee ERROR au niveau de la trx01.
Si c'etait possible, @guyfrancoeur aurait du le mettre dans la definition (syntaxe) pour la trx01.
Voici la definition: 
- `<timestamp> 01 <etat>`
- `<size_t> 01 <ETAT_TARMAC = 0, ETAT_DECOLLAGE, ETAT_VOL, ETAT_ATTERRISSAGE, ETAT_ETEINT>`

**Comment by RmannDev** [comment]
hum!!! je ne sais pas, mais on voit ETAT dans la description de la trx06. 

- 06 <VOLET=11,SH,AI,**ETAT**|[15-19]> <size_t> [ ... ]

**Comment by Eben99** [comment]
[15-19] représente l'intervalle des données possible pour représenter un état de l'avion. Par exemple 15 = état tarmac, 16 = état décollage etc.

**Comment by cryptoswarm** [comment]
@Eben99 
06 <VOLET=11,SH,AI,ETAT|[15-19]> <size_t> [ ... ]
VOLET=11
SH = 12
AI = 13
ETAT = 14
[15-19] veut dire les autres systèmes.

**Comment by brazhia-d** [comment]
@cryptoswarm 
lorsque tu dit : 
ETAT =14 
[15-19] veut dire les autres systèmes.

On associe les numéros 15 , 16, 17, 18, 19 aux fonctions qui n'ont pas été nomées dans l'ordre dont elles apparaissent dans le fichier flop.h ?
Dont, 
15 = Tarmac
16 = Decollage
...
19

**Comment by cryptoswarm** [comment]
@brazhia-d  
d'autres systèmes, rien avoir avec les systèmes 11 -14. 
la seule donnée qu'on a pour traiter leurs états est la transaction 05.
