### ISSUE TITLE
TP2 : Question: ERROR et systeme en erreur

### ISSUE THREAD

**Issue by cedricwtkUQAM** [guyfrancoeur/INF3135_H2020#153]
La troisieme instance d'erreur provoque le message TRX 06. 
Mais dans la situation ou 2 messages ERROR apparaissent dans des transactions TRX 02 (Angle incidence) et la troisieme apparait dans une TRX 03 (ouverture volets).
Quel systeme devons nous mettre en failure? VOLET ou AI?

Ou est ce que le TRX 06 est produit seulement si 3 ERROR sont provoqués par le meme systeme?

**Comment by kicak2009** [comment]
``
Ou est ce que le TRX 06 est produit seulement si 3 ERROR sont provoqués par le meme systeme?
``
Oui, c'est exact. Ce serait plus simple de reconnaître quel système a fait planter 3 fois.

**Comment by cedricwtkUQAM** [comment]
Donc si un systeme provoque 2 ERROR et un systeme different provoque 1 ERROR. Nous ne generons pas le TRX 06?

**Comment by kicak2009** [comment]
Oui, en effet! Et puis, c'est fort possible qu'on peut avoir 2 messages d'erreurs de suite avec différents système : 
```
06 11 191 3X
09 MCAS OFF
06 13 192 3X
```
Alors qu'on sait qu'il y avait eu 2 erreurs dans VOLET et ANGLE INCIDENCE avant de recevoir un erreur dans VOLET et un autre dans ANGLE INCIDENCE.

**Comment by hydraslahir** [comment]
## Capteur
Ce n'est pas lié au sytème, mais au capteur d'un système!
Quand un CAPTEUR donner ERROR 3x, le système correspondant est désactivé.
> Si un capteur donne ERROR, vous devez réagir à la troisième manifestation de ERROR;

Ainsi, si j'ai:
* 101 2 A1 ERROR
* 102 2 A1 ERROR

* 103 2 A2 ERROR //Le système est encore bon
* 104 2 A2 ERROR // encore bon

* 105 2 A1 14
* 106 2 A1 ERROR // (1 seul ERROR sur A1, reset à la ligne 105, ENCORE bon)

* 107 2 A2 ERROR
--> 06 13 107 3X
--> 09 MCAS OFF

Le système AX ne peut pas être réactivé tant que A2 n'a pas reçu une valeur.
### Réflexions pour vous:
* La valeur doit-elle être valide pour réactiver A2, ou une valeur numérique quelconque permet de réactiver A2 et le système AX par la même occassion.?
* Quand le système se réactive, va-t-il comparer sa valeur avec (A1 =14) de la ligne 105, ou devra-t-on avoir A1 de nouveau?
  Ex: 108 2 A2 15
     --> 09 MCAS ON
     --> 06 13 108 MARGE //car 15 -14 > 0.250
     --> 09 MCAS OFF

**Comment by kicak2009** [comment]
Salut @hydraslahir,

Je suis plus ou moins d'accord avec votre argument. En fait, dans l'énoncé comme ceci : 
> Si un capteur donne ERROR, vous devez réagir à la troisième manifestation de ERROR;

C'est pas précisé s'il faut **une série de suite** d'ERROR pour déclencher le MCAS en off ou encore le nombre d'ERROR se réinitialise à **zéro** dès que le capteur reçoit une valeur valide. Si c'est le cas, on part de loin là!

Pour ma part, quand le système se réactive, c'est en validant les deux valeurs reçus. Ainsi, ce sera plus fiable et plus simple.

Cela dit, tu as raison à propos pour le capteur et non le système. J'avais pas pensé à ça, mais en réfléchissant, selon que le prof avait dit en classe, il faut s'attendre que le A3 vienne en back-up si A1 ou A2 est en ERROR. Enfin, je ne sais pas si A3 doit être **automatiquement** détecté dans ce genre de situation... 

Supposons que si A3 se réveille quand A1 ou A2 rencontre une erreur  : 
```
...
171 02 A1 5.5
172 02 A2 ERROR   <-- Première erreur
173 02 A3 5.6     <-- MCAS est toujours actif, car le résultat est valide entre A1 et A3
174 02 A2 ERROR   <-- Deuxième erreur
175 02 A1 4.9
176 02 A3 ERROR   <-- Troisième erreur, MCAS en OFF
177 02 A2 5.05
178 02 A1 5.1     <-- MCAS en ON
...
```
Mais si on ne s'attend pas à A3 aussitôt rencontré une erreur, alors : 
```
...
171 02 A1 5.5
172 02 A2 ERROR   <-- Première erreur
173 02 A2 5.6     <-- A1 et A2 sont valides, MCAS est encore ON
174 02 A2 ERROR   <-- Deuxième erreur
175 02 A1 4.9
176 02 A2 5.05    <-- Encore là, MCAS est toujours ON
177 02 A2 ERROR   <-- Oups, troisième erreur, MCAS en OFF!
178 02 A1 5.1  
179 02 A2 ERROR   <-- Première erreur
180 02 A1 ERROR   <-- Deuxième erreur
181 02 A2 7.2
182 02 A1 5.0     <-- Affiche "MARGE", mais MCAS toujours OFF
183 02 A2 7.1
184 02 A1 7.2     <-- MCAS en ON
...
```
Comme vous pouvez voir, la ligne 184 restaure le système fonctionnel car il a reçu 2 valeurs (A2 = 7.1 et A1 = 7.2) qui sont valides.
Enfin bon... c'est juste mon hypothèse. Faudrait voir que le prof en pense.

**Comment by hydraslahir** [comment]
C'est intéressant d'avoir une autre perspective.
Les valeurs dans tes 3 capteurs se réinitialisent lorsque tu as ERROR si je comprends bien.
De mon point de vue, un capteur A2 en ERREUR ne devrait pas affecté les valeurs existantes des autres capteurs.

### Reprise de l'exemple
Si je reprends ton exemple 1, on peut voir que nos codes agissent de façon complèment différentes!
```html
171 02 A1 5.5
172 02 A2 ERROR   <-- A2 error =1  -->
173 02 A3 5.6     <-- MCAS est toujours actif, car le résultat est valide entre A1 et A3 -->
174 02 A2 ERROR   <-- A2 error = 2 -->

175 02 A1 4.9  ++++++++++++++++++++++++++ 08 MARGE A1 A3 (MCAS OFF)

176 02 A3 ERROR   <-- A3 error = 1 et A2 error = 2-->

177 02 A2 5.05    +++++++++++++++++++ A2 error=0; A1 et A2 valides, MCAS ON>.
```
Mon approche de conserver les anciennes valeurs après une mauvaise marge est simple. Les valeurs étaient valides, elles le sont encore, c'est la différence qui est invalide.

### consernant les 3 ERRORS sur le même capteur
Le cas 04 dans le TP.md semble nous amener à penser que ce sont 3 ERRORS sur le même capteur 
![image](https://user-images.githubusercontent.com/55253792/77238213-b6913680-6ba4-11ea-80c2-4264a9ec363e.png)

D'ailleurs, en considérant les 3 capteurs en même temps, tu ne sais pas quand ton système est de nouveau réellement actif.
On le voit notamment à la ligne |178| dans ton 2e exemple, ça cause un problème. 3 ERROR qui ferment le MCAS, bien. Néanmoins, n'importe quelle valeur valide(comme 179) va le réouvrir **automatiquement**. C'est inutile d'avoir la validation d'ERROR si cela ferme le MCAS pendant 1ms à tous les coups.
Si tu as:
```
100 2 A1 ERROR
101 2 A2 ERROR
102 2 A3 ERROR
```
La seule manière de savoir avec certitude si ton système AX est réellement opérationnel c'est d'avoir une valeur valide sur tes capteurs A1, A2 ET A3, car les trois contribuent à l'échec.

Mais bon, on verra bien ce que le prof pense de tout ça ^...^

**Comment by kicak2009** [comment]
Ce n’est pas bête de ton point de vue, j'avoue que c'est plus convaincant! 

>  3 ERROR qui ferment le MCAS, bien. Néanmoins, n'importe quelle valeur valide(comme 179) va le réouvrir **automatiquement**.  

En fait, j'ai peut-être mal exprimé, mais ce n'est pas n'importe quelle valeur valide qui ramène le MCAS en ON, c'est plutôt les deux valeurs valides après vérification de **marge**. C'est pour ça que la ligne 184 dans mon deuxième exemple fait passer MCAS à ON.

Aussi, je réinitialise aussi les valeurs quand la décision de comparer entre les deux valeurs a été faite : 
```
101 02 A1 8.2    <-- Pas de décision à prendre.
102 02 A2 8.25   <-- A1 et A2 ont été comparé et sont valide. Je remets A1 et A2 à zéro. 
103 02 A2 5.0
104 02 A1 4.9    <-- Encore là, c'est valide aussi. Et je réinitialise ces deux valeurs. 
105 02 A1 11.0
106 02 A2 ERROR  <-- Première erreur, mais A1 est toujours à 11.0.
107 02 A3 10.8   <-- A1 et A3 sont valides, je les remets à zéro.
108 02 A2 0.4
109 02 A1 99.0   <-- Aie, erreur de MARGE et <MCAS OFF>, mais A2 n'a pas changé.
110 02 A1 0.25   <-- 0.25 écrase 99.0, donc ils sont valides et remis à zéro. <MCAS ON> 
```
Ironiquement, pendant que j'écris, il y a un détail qui me chicote. C'est vrai que ce serait plate de fermer MCAS pendant 1 ms comme je viens de faire dans ces deux dernières lignes de mon exemple... 

Bref, comme j'ai dit plus haut, je ramène le système opérationnel quand **au moins** 2 valeurs sont valides, peu importe le AX. Et je supprime les valeurs par la suite, comme après **3x ERROR**, pour éviter les incohérences à mon avis.

Et puis, peut-être que le prof est plus flexible qu'on pense donc il pourrait accepter nos deux points de vue ahah!

**Comment by hydraslahir** [comment]
Je doute que le prof soit bien flexible sur ça, mais c'est possible.

Je vois que tu travailles en Duo et que tu remets à 0, j'avais pensé à ça et j'ai changé de stratégie assez rapidement, il y avait beaucoup de détails de syncronisation que je n'aimais pas! Si tu les gères, bravo! 

Même sur cette section nos codes génèrent des trucs plutôt différents(le mien MCAS OFF à 103 par exemple)!

Bref, on verra ce que le prof en pense je suppose ^__^

**Comment by cedricwtkUQAM** [comment]
Clairement que non! La correction des fonctionnalités est par comparaison binaire. C'est a dire comparaison des vos resultats et des siens. Si ca match +1 sinon 0. 
D'ou la difficulté de ce TP car l'énoncé est flou pas mal.

**Comment by LorenaMedina** [comment]
> 105 2 A1 14
>     106 2 A1 ERROR // (1 seul ERROR sur A1, reset à la ligne 105, ENCORE bon)
>     107 2 A2 ERROR
>     --> 06 13 107 3X
>     --> 09 MCAS OFF
> Le système AX ne peut pas être réactivé tant que A2 n'a pas reçu une valeur.
> Réflexions pour vous:
>     La valeur doit-elle être valide pour réactiver A2, ou une valeur numérique quelconque permet de réactiver A2 et le système AX par la même occassion.?
>     Quand le système se réactive, va-t-il comparer sa valeur avec (A1 =14) de la ligne 105, ou devra-t-on avoir A1 de nouveau?
>     Ex: 108 2 A2 15
>     --> 09 MCAS ON
>     --> **06 13 108 MARGE //car 15 -14 > 0.250**
>     --> 09 MCAS OFF
> 

Commentaire: Pour les lignes 108, d'après autres issues la ligne 106 , écrasé la valeur de la ligne 105,  Voir issue #138, donc d'après moi en ne peut pas faire ce calcul de MARGE.

**Comment by hydraslahir** [comment]
Revoyons l'issue 138 ensemble: 
### Code:
```
156 03 D 12.100
161 03 D -1.700
167 03 G ERROR
170 03 G 10.000
```

### Réponse:
![image](https://user-images.githubusercontent.com/55253792/77259984-54473d00-6c5b-11ea-95db-d1d66abeba14.png)

### Suite:
L'issue #138 ne fait pas la comparaison parce que la valeur -1.7 est invalide et INUTILISABLE. Reprennons l'exemple SANS cette ligne nuisible.
```html
156 03 D 12.100
167 03 G ERROR
170 03 G 10.000
```
La valeur 12.100 est valide pour le D.
La valeur de 12.100 est STABLE et UTILISABLE, pourquoi ne pas l'utiliser ? 
(Tu noteras que personne ne parle de cette ligne, tout le monde se focalise sur la méchante valeur -1.7).

Conclusion, je pense qu'il faut comparer 12.100 et 10.000 puisque les deux valeurs sont STABLES à ce moment dans le code ET UTILISABLES.

## Le problème soumis et ce que je pense du résultat.
```html
(... A2 error = 2)
...
105 2 A1 14
106 2 A1 ERROR   <-- ERROR est un signal disant que la valeur émisse ne peut pas être lue -->
                         <--la valeur 14 RESTE STABLE et UTILISABLE. -->
                         <-- ERROR ne fait rien TANT qu'il n'y a pas 3 occurences consécutives! -->
107 2 A2 ERROR  <-- A2 error = 3-->
    --> 06 13 107 3X
    --> 09 MCAS OFF
108 2 A2 15          <--  La chute du capteur A2 ne doit pas 
                    <-- affecter la validité de la lecture antérieure du capteur A1 
                    <-- A1 et sa valeur ne sont pas affectés et sont encore valides! -->
    --> 07 (...)
    --> 09 MCAS ON
    --> 06 13 108 MARGE
    --> 09 MCAS OFF
                              <-- Note, la variation du MCAS est affichée ici que pour démonstration!! -->
                       <-- La sortie réelle serait probablement 06 13 108 MARGE seulement -->
```
Nous avons les informations nous permettant de prendre une décision à la ligne 108. A1=14 et A2=15.
Dans un monde idéal, ce problème serait géré en regardant une variation de TimeStamp. Exemple, si A1 n'a pas donné d'information après 500ms, sa valeur ne devrait pas être utilisée.
Dans notre TP, ce détail est ignoré, on fait avec.

ERROR n'est pas une valeur et ne devrait pas être considérée comme telle, c'est une information nous signalant que la lecture du capteur s'est mal faite. Cela ne devrait pas écraser la valeur de son capteur!

**Comment by guyfrancoeur** [comment]
Allo,

Réponse pour tous pas l'auteur.  J'aurais pu rien dire mais tu as mis le doigt directement sur le PROBLEME DE BOEING.

Si tu pense comme ca l'avion va s'écraser.
Tu ne fait pas le programme pour toi.
Tu dois penser comme un Ingénieur. Pas de sentiment.
Il ne faut rien assumer.  Oulbli les ms.  Oubli les SI.  Ca ne sert pas la cause.

Si le sensor te donne une valeur tu dois la prendre même si elle n'est pas bonne.

Pourquoi ?

Car le sensor te la donne. Il est rendu la.  S'il donne une fausse valeur ça veut dire qqc.

IL EST PEUT ÊTRE BRISÉ !  

1. Tu ne dois jamais faire une correction de données (cette altération est dangereuse et n'est pas souhaitable.)
2. Pourquoi retourner dans le temps et prendre la valeur qui te plait ?

Parce que c'est plus facile, plus beau, moins plate.

NON, TU DOIS FAIRE AVEC CE QU'ON TE DONNE.

Il y a beaucoup trop de SI et d'émotion dans ta prise de décision.  
Je ne dis pas que dans la vie c'est mal.  **Mais pour faire un programme ca n'est pas utile.**

G
