### ISSUE TITLE
MCAS ON

### ISSUE THREAD

**Issue by LorenaMedina** [guyfrancoeur/INF3135_H2020#154]
J'aimerais savoir un petit résumé des exigences pour déterminer si le système (11-14)  par exemple volet=11, est fonctionnel?

J'ai des doutes car maintenant une valeur inacceptable avec trx 08 ne cause pas un MCAS off.
Merci pour vos réponses.

**Comment by hydraslahir** [comment]
Il en cause un, il n'est juste pas **affiché**.

**Comment by guyfrancoeur** [comment]
Allo,

Comment avez vous traité le cas?

Exemple et résolution.

**Comment by LorenaMedina** [comment]
De mon côté, la phrase de l'ennoncé:
> 08: Détection d'une valeur inacceptable provenant de senseurs
> Cette transaction ne déclenche pas l'affichage de 09 MCAS OFF

- Je l’ai interprété comme quoi on ne met pas MCAS à OFF et on n'affiche pas .
Cela je l'ai trouvé en contradiction au fait que la valeur n'est pas correcte (disons pour le volet -1.70). Dans ma version originale j'avait considéré qu'un système est correct *sans erreurs* pour: (issue #114). 
- Valeur inacceptable
- Marge
- Pour les volets : pas ouverts
- Pas 3 ERRORS
- Pas seuil critique (SH)
Donc je mettais à OFF, j'affichait et plus système pas fonctionnel.

- Maintenant , d'après la réponse de  hydraslahir:
1. On met MCA à OFF
2. On n'affiche pas cela.
3. Système n'est pas fonctionnel (pour l'analyse du MCA ON)

C'est bien ça le fonctionnement actuel?.
Merci.

**Comment by guyfrancoeur** [comment]
Bonjour,

Nous ne pouvons pas mettre le MCAS à OFF avec un seul capteur/sensor en erreur.  Il y a beaucoup de capteur dans un avion. Puisque nous avons plusieurs capteurs il n'est pas logique de prendre une décision avec un seul capteur.

La trx 08 dit que la valeur dans le capteur n'est pas bonne. ok. c'est tout. est-ce assez pour fermer le MCAS ? non !

Cordialement,

**Comment by MoonscriB** [comment]
Mr guyfrancoeur, j'aimerais vous rediriger au cas #114 où vous répondez à LorenaMedina que tous les cas qu'elle/il expose sont bien définis.  Or, son cas2 dis bien "capteur donne une valeur inacceptable".

Je ne sais pas si c'est seulement moi, mais j'ai de plus en plus de mal à faire sens d'instructions qui me semblent parfois aller jusqu'à se contredire.

**Comment by guyfrancoeur** [comment]
Oui, mais à la premiere occurence ou la deuxième,

Moi je dis que nous allons prendre une décision après la reception de la deuxième occurence (ou confirmation) d"un capteur.

**Comment by cryptoswarm** [comment]
@guyfrancoeur 
102 03 G 201.10   n'est pas conforme car l'ouverture > longueur maximale d'un volet
103 03 D 0.125  n'est pas ouvert, la borne inférieur pour considérer un volet ouvert est 0.9. 

comment avez vous pu calculé la marge ?

**Comment by RmannDev** [comment]
@cryptoswarm, effectivement comment calculer la marge. On a:
102 03 G 201.10 => valeur non conforme
103 03 D 0.125 => encore une valeur non conforme,
A mon sense on cherche à calculer la marge (l'écart entre les 2 longueurs) après avoir verifier que les deux valeurs soient conformes. ce qu'on ne peut pas faire dans ce cas parce que les 2 valeurs qui devraient nous servir à calculer cette marge ne sont pas conforme.

**Comment by guyfrancoeur** [comment]
Allo,

C'est vrai ouille vive les logiciel car les humains ca fait des erreurs.  Merci @cryptoswarm 

entrée

```
102 03 G 201.10 <-- valeur conforme ou pas?
103 03 D 0.125 <-- ici les vérifications pour MARGE, OUVERTURE 
                          (pour savoir si le système ferme et le MCAS reste ouvert)
```
sortie :
```
08 11 102 G
```

Le capteur G revient a la valeur par défaut et nous ne pouvons pas calculer la MARGE.

Consulter #160 et [ici](https://github.com/guyfrancoeur/INF3135_H2020/blob/master/tp/tp2-%C3%A9nonc%C3%A9.md#r%C3%B4le-de-votre-programme)

Cordialement,
