### ISSUE TITLE
TP2 : Est-ce que le partage de scénarios de tests, est une bonne idée ?

### ISSUE THREAD

**Issue by guyfrancoeur** [guyfrancoeur/INF3135_H2020#156]
Bonjour,

Si je vous laisse partager des petits scénarios de tests cad : des lignes de transactions (entrée) et que vous executé votre programme dessus et que vous publié votre sortie est-ce une bonne idée ?

Au lieu de spéculer sur les résultats vous allez tester vos programmes sur des valeurs en entrée et publier des valeurs en sortie.  Il est certain que ceci peut devenir problématique pour certains. Vous devez avoir une certaine confiance en votre jugement pour vous lancer dans cette aventure.  Car le doute peut devenir assez 😵 dizzy.

Rien n'est dit si les résultats sont bons mais peut-être que je vais moi même les exécuter et commenter si c'est bon ou acceptable.

Si vous pensez que ceci est bien on réagit au post !

**Comment by cedricwtkUQAM** [comment]
J'aime l'idee. Au moins on aura des informations sur la production d'ensemble et la comprehension d'ensemble

**Comment by cryptoswarm** [comment]
`91 01 0
110 01 1
120 01 9
124 02 A1 5.5
125 02 A2 ERROR
129 02 A3 5.6
141 02 A4 10.5
142 02 A1 377.29
144 02 A1 12.125
145 02 A2 24.250
145 03 G 0.0            
146 03 D 1.0019
151 03 G 11.200
156 03 D 12.100
161 03 D -1.700
167 03 G ERROR
170 03 G 10.000
171 03 G 12.500
172 03 D 24.500
175 04 G 0.5
176 04 D ERROR
176 04 G 0.56
178 04 D ERROR
179 04 D ERROR
183 05 19 911
185 05 19 0
191 05 15 1
198 05 16 2
199 05 15 0
200 05 16 0
201 05 14 0
202 05 13 0
203 05 12 0
205 05 17 0
206 05 18 0
207 05 11 0
208 02 A1 1000
220 03 G -50
230 03 D 2
`
ce qui donne comme output :

`08 14  120 9
08 13 142  A1
06 13  145  MARGE
09 MCAS OFF
09 MCAS OFF  // un seul affichage indiquant que les volet sont ouverts
08 11  161  D     
06 11  172  MARGE
06 12 179 3X
09 MCAS OFF
06 19 183
09 MCAS OFF
07 19 185
06 15 191
09 MCAS OFF
06 16 198
09 MCAS OFF
07 15 199
07 16 200
07 14 201
07 13 202
07 12 203
07 17 205
07 18 206
07 11 207
09 MCAS ON
08 13 208  A1
08 11  220  G
09 MCAS OFF
06 11  230  MARGE
`

**Comment by MaximCrudu** [comment]
D'après ce que j'ai compris selon l'enocé: "les trx 06 sont utilisés avec les trx 07". Autrement dit, si une transaction d'un système externe (exemple: 206 05 18 0) ne corrige aucune erreur entrée précédemment, donc 07 ne sera tout simplement pas affiché car elle n'a aucun impact qui change l'état du système.

**Comment by guyfrancoeur** [comment]
Voici 

### Le début de ma réponse

```
version #: 0.0.10009
06 14 120 ETAT
08 13 142 A1
09 MCAS OFF
09 MCAS OFF
08 11 161 D
06 11 172 MARGE
09 MCAS OFF
08 12 179 3X
09 MCAS OFF
...
```

Réagissez à ce post.

**Comment by TringaAxel** [comment]
Allo ! 

Je suppose qu'il y a un problème dans l'affichage, pourquoi fermer 2 fois le MCAS alors que si on le détecte déjà une fois on a pas besoin de le re-éteindre.
Normalement la sortie aurait du être : 
```
06 14 120 ETAT
09 MCAS OFF
08 13 142 A1
08 11 161 D
06 11 172 MARGE
08 12 179 3X
```
Tant qu'on le rallume pas ça ne sert a rien de l'éteindre encore et encore.

**Comment by cryptoswarm** [comment]
> Voici
> 
> ### Le début de ma réponse
> ```
> version #: 0.0.10009
> 06 14 120 ETAT
> 08 13 142 A1
> 09 MCAS OFF
> 09 MCAS OFF
> 08 11 161 D
> 06 11 172 MARGE
> 09 MCAS OFF
> 08 12 179 3X
> 09 MCAS OFF
> ...
> ```
> 
> Réagissez à ce post.

`144 02 A1 12.125`
`145 02 A2 24.250`
le timeStamp est correcte
l'angle d'incidence est entre 2.5 et 51 
la marge entre l'angle donné par le capteur A1 et A2 > 0.25

Question : quelle est la raison pour laquelle  `06 13 145 MARGE` n'est affiché?

**Comment by cedricwtkUQAM** [comment]
Je suis daccord avec @TringaAxel , pourquoi afficher plusieurs fois le MCAS OFF?

**Comment by guyfrancoeur** [comment]
Bonjour,

Merci pour les commentaires 👍 

@TringaAxel et autres
Parce que c'est dans les demandes et requis du travail.
Comme mentionné nous ne faisons pas le logiciel pour qu'il soit apprécié par l'humain. C'est le dialogue (liste des événements) pour les boites noires.

@tous
À partir de maintenant il ne faut plus faire du *debug* spéculatif. Assumer des choses ou laisser le hasard décider.  Les posts sont pour réaliser un logiciel, avec des techniques et de la science.

@tous les commentaires non pertinent, ou sans valeur ne seront plus tolérés.

Vous devez faire la démonstration, une trace informatique *PAS HUMAINE*. Afin de suivre et comprendre le logiciel et son résultat.

**Comment by cedricwtkUQAM** [comment]
Pourquoi est ce que le timestamp 141 ne produit pas d erreur 08? La donnée A4 est une donnée impossible pourtant!
Elle devrait afficher 08 13 141 A4 non?

**Comment by cryptoswarm** [comment]
> Pourquoi est ce que le timestamp 141 ne produit pas d erreur 08? La donnée A4 est une donnée impossible pourtant!
> Elle devrait afficher 08 13 141 A4 non?

A4 n'existe pas

**Comment by guyfrancoeur** [comment]
Allo,

@cedricwtkUQAM et @cryptoswarm 

relire #160 svp. et énoncé on a parler de ceci souvent.  Vos commentaires conduisent les gens vers l'erreur.

@tous qui ont déjà assez contribuer, limitez vos posts laissez la chance a d'autres svp.

Je vais pris les autres de ne pas lire les deux commentaires précédent.

**Comment by leopoldmaillard** [comment]
> Voici
> ### Le début de ma réponse
> 
> ```
> version #: 0.0.10009
> 06 14 120 ETAT
> 08 13 142 A1
> 08 13 145 MARGE   // j'avais mis un commentaire dans mon programme ... ouille désolé
> 09 MCAS OFF
> 09 MCAS OFF
> 08 11 161 D
> 06 11 172 MARGE
> 09 MCAS OFF
> 08 12 179 3X
> ...
> ```
> 
> Je ne _debug_ pas la réponse dans le issue. wink
> 
> Si le résultat n'est pas conforme à une ligne de l'énoncé, vous me le dites. On fera un appel zoom pour 10 minutes afin d'en faire la preuve.
> 
> Réagissez à ce post.

Bonjour,
Pourquoi la ligne ```06 14 120 ETAT``` ne serait pas suivie d'un ```09 MCAS OFF``` ? Cela devrait être le cas selon l'énoncé.
Merci d'avance !

**Comment by phsoucy** [comment]
@leopoldmaillard : @guyfrancoeur a spécifié lors du zoom de lundi qu'un état invalide ne fermait pas le MCAS. Or, selon l'énoncé (considérant que l'état est un système et non pas un capteur), on doit effectivement fermer le MCAS... Il y a donc incohérence.

```
06: Détection des erreurs de système

    06 <système> <timestamp> [information additionnelle]
    06 <VOLET=11,SH,AI,ETAT|[15-19]> <size_t> [ ... ]
    Après cette transaction il y aura affichage de 09 MCAS OFF.
```

**Comment by guyfrancoeur** [comment]
Allo,

D'accord on va ajouter MCAS OFF pour pour suivre l'énoncé tu as raison.

Bien vu.

**Comment by lisacsn** [comment]
@guyfrancoeur 

```
06: Détection des erreurs de système

    06 <système> <timestamp> [information additionnelle]
    06 <VOLET=11,SH,AI,ETAT|[15-19]> <size_t> [ ... ]

    Après cette transaction il y aura affichage de 09 MCAS OFF
```

**Comment by phsoucy** [comment]
J'avais pourtant répondu avec l'extrait de l'énoncé, mais il a supprimé mon post...

**Comment by phsoucy** [comment]
> Voici
> ### Le début de ma réponse
> 
> ```
> version #: 0.0.10009
> 06 14 120 ETAT
> 08 13 142 A1
> 08 13 145 MARGE   // j'avais mis un commentaire dans mon programme ... ouille désolé
> 09 MCAS OFF
> 09 MCAS OFF
> 08 11 161 D
> 06 11 172 MARGE
> 09 MCAS OFF
> 08 12 179 3X
> ...
> ```

Pourquoi `08 13 145 MARGE` génère un `08` alors que `06 11 172 MARGE` un `06`? Je pensais que des marges non valides généraient un `06` puisque c'est selon l'information de deux capteurs différents, donc d'un système.

**Comment by assilg** [comment]
> > Voici
> > ### Le début de ma réponse
> > ```
> > version #: 0.0.10009
> > 06 14 120 ETAT
> > 09 MCAS OFF  <-- pas bon ca. Je donne la réponse ATTENTION, dans le prochain post.
> > 08 13 142 A1
> > 06 13 145 MARGE   // j'avais mis un commentaire dans mon programme ... ouille désolé
> > 09 MCAS OFF
> > 09 MCAS OFF
> > 08 11 161 D
> > 06 11 172 MARGE
> > 09 MCAS OFF
> > 08 12 179 3X
> > ...
> > ```
> > 
> > 
> > Je ne _debug_ pas la réponse dans le issue. wink
> > Si le résultat n'est pas conforme à une ligne de l'énoncé, vous me le dites. On fera un appel zoom pour 10 minutes afin d'en faire la preuve.
> > Réagissez à ce post.
> 
> Bonjour,
> Pourquoi la ligne `06 14 120 ETAT` ne serait pas suivie d'un `09 MCAS OFF` ? Cela devrait être le cas selon l'énoncé.
> Merci d'avance !

Allo 

as tu su la réponse du pourquoi ?
Si oui, tu peux répondre à mon message stp parce que je trouve ça bizarre aussi.

Merci bien.

**Comment by cedricwtkUQAM** [comment]
Parce que il n y a pas changement d ETAT

**Comment by bachmaroua** [comment]
pour 
91 01 0
110 01 1
120 01 9 // attention voir en bas ! GF
124 02 A1 5.5
125 02 A2 ERROR
129 02 A3 5.6
141 02 A4 10.5
142 02 A1 377.29
144 02 A1 12.125
145 02 A2 24.250 


on aura comme sorti 
version #: 0.0.10009
06 14 120 ETAT
08 13 142 A1
06 13 145 MARGE


d'apres la deuxième ligne l'etat de l'avion est 1 , l'avion est en decollage : 
DECOLLAGE entre 2.5 ET 51.0
alors pourquoi 145 02 A2 24.250 nous genere un code 06 13 145 MARGE
est ce que c'est parce que l'avion revient a l'etat 0 suite a 06 14 120 ETAT ?? 
si c'est le cas pourquoi 144 02 A1 12.125 ne genere aucun code (TARMAC entre 0.2 et -0.2)

**Comment by guyfrancoeur** [comment]
Allo, 

La **marge**, la différence (trop grande), entre les deux valeurs recu.

G
