### ISSUE TITLE
Imprission de la version

### ISSUE THREAD

**Issue by cryptoswarm** [guyfrancoeur/INF3135_H2020#157]
Qu'est ce qui manque dans le code ci-bas pour qu'il imprime la version.
`int main()`
`{`
`version_t *ver;`
`flop_version(ver);`
`printf("%s%u%s%u%s%d\n","version #:", ver-> major,".",ver-> minor,".", ver-> build);`

Quand je compile j'obtiens un warning disant que  `ver` n'est pas initialisé.
A l'execution de ./tp2 j'obtient `Segmentation fault`

**Comment by guyfrancoeur** [comment]
Allo,

Comment fait-on pour initialiser ce type de variable ?
Quel est le type de `ver` ou c<est quoi `ver` exactement ?

G

**Comment by cryptoswarm** [comment]
J'ai essayé avec `version_t *ver=NULL`
pas de warning mais ca ne règle pas le problem de `Segmentation fault`

**Comment by guyfrancoeur** [comment]
Rallo,

Bien une chose de fait, mais pas nécessaire, ici. C'est quoi `ver` ?
Comment faire pour `RÉSERVER` de l'espace mémoire pour utiliser ce type de variable ?

Éditer ton post svp.

**Comment by cryptoswarm** [comment]
`version #:0.0.10009` 
problem reglé  without any warning.

**Comment by guyfrancoeur** [comment]
Je sais! 😜
