### ISSUE TITLE
TP2 : Système de nouveau fonctionnel

### ISSUE THREAD

**Issue by Marie287** [guyfrancoeur/INF3135_H2020#159]
Bonjour,

J'ai quelques doutes à propos de la transaction 07. Je comprends comment procéder pour les systèmes [15-19], mais pour ce qui est des systèmes [11-14], j'ai un peu de mal à comprendre ce qu'il faut prendre en compte.

> 07: Système de nouveau fonctionnel
> + ```07 <système> <timestamp>```
> + ```07 <VOLET=11,SH,AI,ETAT|[15-19]> <size_t>```
> > > + Après cette transaction on pourrait afficher `09 MCAS ON`, si aucun autre système est en erreur.

Pour savoir si aucun système est en erreur, il suffit de vérifier si aucun des capteurs n'est actuellement en "ERROR" ? Ce serait la seule condition pour générer un MCAS ON ?  
Puisque dans l'énoncé il est aussi écrit que les systèmes en erreurs sont ceux pour lesquels une trx 06 a été générée.  Il est aussi indiqué que ` les trx 06 sont utilisées avec les trx 07`

Moi je pensais aussi vérifier qu'aucun volet n'est actuellement ouvert, et que les systèmes n'ont pas d'erreur de MARGE avant de remettre le MCAS à ON.
En gros, pour remettre le MCAS à ON, je pensais vérifier si tous les systèmes qui ont produit un "MCAS OFF", ont corrigé leur erreur (ont produit une MARGE bonne, ou ont fermé leur volets par exemple).  
  

  

Et en ce qui concerne le MCAS OFF pour la transaction 08, il y ceci dans l'énoncé : 

> > + Après cette transaction il n'y a pas automatiquement d'affichage `09 MCAS OFF` voir en trx `09`.
> > + Pour savoir si on ferme le MCAS, valider avec le maximum de données (2 valeur pour VOLET, AI, SH).  

Je voulais être sure de bien comprendre : pour mettre le MCAS à OFF pour cette transaction, il faut qu'au moins deux capteurs du même système aient produit une trx 08 ?

**Comment by benoit-dubreuil** [comment]
> Pour savoir si aucun système est en erreur, il suffit de vérifier si aucun des capteurs n'est actuellement en "ERROR" ?

Ce ne sont pas les systèmes qui sont en "ERROR", mais les capteurs. Alors, un seul "ERROR" n'affecte aucun système. Or, 3 "ERROR" consécutifs pour le même capteur génère un trx `06` et donc ça devient une erreur système.

Comme @guyfrancoeur a dit au #114, ce qui maintient le MCAS OFF c'est une pile (tas) de problèmes. Par exemple, tu pourrais avoir plusieurs erreurs systèmes différentes. Un exemple serait 3 "ERROR" consécutifs en plus d'un trx `01` avec 9 comme paramètres. L'état est un système, donc il serait lui aussi en erreur.

> En gros, pour remettre le MCAS à ON, je pensais vérifier si tous les systèmes qui ont produit un "MCAS OFF", ont corrigé leur erreur (ont produit une MARGE bonne, ou ont fermé leur volets par exemple).

C'est exactement ça qu'il faut faire.

> Je voulais être sure de bien comprendre : pour mettre le MCAS à OFF pour cette transaction, il faut qu'au moins deux capteurs du même système aient produit une trx 08?

Je crois que c'est aussi exactement ça qu'il faut faire.

**Comment by guyfrancoeur** [comment]
Bien résumé.

**Comment by Marie287** [comment]
Merci beaucoup pour la réponse, je comprends mieux maintenant !
