### ISSUE TITLE
TP2 : Détails d'implémentation à mettre dans votre programme

### ISSUE THREAD

**Issue by guyfrancoeur** [guyfrancoeur/INF3135_H2020#160]
Bonjour,

Merci à Éric pour la réflexion. Les autres qui aussi détecté/trouvé UN GROS BRAVO.

## Détails d'implémentation à inclure dans votre programme.
Les détails qui suivent sont ceux que vous auriez dû découvrir durant le travail.

#### Les cas suivants sont des exemples : 
 - a) `17 03 G -1.700`
 - b) `18 03 D ERROR`
 - c) `19 04 G ERROR`
 - d) `20 03 G 109.09`
 - e) `21 02 A1 377.29`
 - f) `22 01 T`
 - ...

### La règle A11 (SH, AI, VOLET)
 - Les valeurs qui ne sont pas acceptables sont gérées et le capteur prend la valeur par défaut.
 - Détail : 
   + La valeur est lue.
   + Selon le cas (ceci veut dire pas toujours) une transaction `08` est générée. { ex a) d) e) }
   + Le capteur est réinitialisé. (avec valeur par défaut) { ex a) .. e) }

```
```

### La règle A12.B L'état de l'avion n'est pas un capteur, c'est un système.
 + Il est impossible de mettre l'état de l'avion en erreur.

### La règle A12.C (ETAT)
  - Les valeurs qui ne sont pas acceptables sont gérées et aucun changement n'est appliqué.
  - Détail : 
    + La valeur est lue.
    + Selon le cas, une transaction `06` est générée. { ex f) }
    + Aucun changement, l'état d'origine est maintenu.

```
```

### La règle A13 ( trx 02 )
  - Les angles reçus, doivent être traités dans l'ordre d'arrivés, premier arrivé premier utilisé.

Exemple
```
...
120 02 A2 10.0 < -- (a)
121 02 A3 10.0 < -- (a)
121 02 A1 18.0    < -- (b)
121 02 A2 ERROR
121 02 A2 19.0    < -- (b)
...
```
Traitements : 
 - On prend A2 et A3 (a) 
 - On remet les défauts 
 - Et après on prendra A1 et A2 (b)

```
```

### La règle A14 ( trx 02, 03, 04 )
 - Vérifier la conformité des angles ou valeurs avant de vérifier la marge.

Traitement : 
 - Il faut deux valeurs pour faire la vérification
 - Si la conformité d'une valeur indique une erreur, il n'est pas nécessaire de vérifier la MARGE
 - Si la conformité des deux valeurs est bonne, il est possible de vérifier la MARGE

```
```

### La règle A15 ( trx 02, 03, 04 )
 - Lorsque nous avons 3X le mot ERROR pour un même capteur cette règle s'applique.

Traitement : 
 - À la troisième occurrence, consécutive, pour ce capteur, du mot ERROR, déclencher une transaction `08`
 - Affecter le capteur à la valeur par défaut
 - Affecter le compteur du capteur de mot ERROR à 0

Réagissez à ce post.

G

**Comment by RmannDev** [comment]
**Où sont les valeurs par défaut ?????** 
selon #160 on a l'état par défaut qui est TARMAC. 
selon l'énoncé on a : 
un angle d'incidence est valide pour les intervalles inclusifs suivants :
- TARMAC entre 0.2 et -0.2 => ces valeurs nous permettent de valider les valeurs dans capteur quand justement l'état de l'appareil est TARMAC. 

**Mais je ne vois pas de valeur par défaut. Où sont les valeurs par défaut svp ????????????**

**Comment by thomasgericot** [comment]
Bonjour,

Je ne comprends pas trop la notion de "desactivation de MCAS" dans la modifciation que vous avez apportee.
Trois occurrences de ERROR pour un capteur n'entrainent pas la desactivation de MCAS ?
On traite cela en renvoyant seulement un trx 08 ?

Merci et bonne journee.
Thomas.

**Comment by benoit-dubreuil** [comment]
Pour la règle `A13`, il est dit :

> Les angles reçus, doivent être **traités dans l'ordre d'arrivés, premier arrivé premier utilisé**.
    - On prend A2 et A3 (a)
    - On remet les défauts
    - Et après on prendra A1 et A2 (b)

Voulez-vous dire qu'on ne traite que 2 capteurs à la fois selon leur ordre d'arrivé peu importe si 3 capteurs sont corrects?

Personnellement, avant que vous indiquiez qu'il fallait affecter les valeurs par défaut après les avoir utilisés, je traitais le plus de capteurs que possible et je gardais leurs valeurs jusqu'à temps que des trx `08` surviennent pour ces capteurs. 

La raison de ce traitement est que, au trx `09` de l'énoncé, 
> Pour savoir si on ferme le MCAS, valider avec le maximum de données (2 valeur pour VOLET, AI, SH).
il est indiqué d'utiliser un maximum de données. Or, j'avais interprété ça comme **au moins** 2 valeurs pour les capteurs. M'étais-je trompé?
