### ISSUE TITLE
flop.h

### ISSUE THREAD

**Issue by thomasgericot** [guyfrancoeur/INF3135_H2020#162]
Bonjour, 

Doit on se servir des fonctions de flop.h pour realiser le tp2(pour verifier si les ecarts entre deux angles/longueurs sont conformes et valides), ou peut on le faire sans avoir recours a ces fonctions et seulement en se renvoyant aux criteres enonces dans "critere d'evaluation pour les fonctions",

Merci pour votre reponse.

**Comment by riadsm** [comment]
Je crois que c'est possible, mais que c'est une très mauvaise pratique.
* Tu refais du code déja fait, c'est inutile et très couteux en entreprise.
* Si les critères changent et que les fonctions dans flop.h changent, il va falloir aller changer ton code aussi, c'est une perte de temps. Juste changer la méthode dans flop.h et boom.
* Pourquoi faire des tests sur des méthodes qu'on n'utilise pas ? 
* Tes méthodes peuvent avoir des erreurs dedans qui vont affecter le résultat de toutes les personnes qui vont uiliser tes méthodes.

* **Tu vas devoir les utiliser dans le TP3** anyway, car on utilise les fonctions dynamiquement.

À mon avis, tu as le droit de ne pas les utiliser, mais c'est une perte de temps, parce que tu n'as **aucune** bonne raison de ne pas les utiliser.

**Comment by thomasgericot** [comment]
merci beaucoup pour ta reponse

**Comment by thomasgericot** [comment]
et donc on considere que toutes les fonctions relatives aux choses qu'on doit verifier (marge d'ouverture des volets, stabilisateur horizpontal,etc) sont fonctionelles ?

**Comment by riadsm** [comment]
En fait, flop.h contient 3 versions de chaque méthode. Une des 3 est valide.
Ex: parmi angle_incidence_marge_v1/2/3, seule v1 est valide.
L'issue #126 contient la liste des fonctions valides. Tu devrais néanmoins être en mesure d'avoir la même liste avec ton TP1.
Mais oui, il y en a 1 et 1 seule de fonctionnelle pour chaque triplet et tu peux les utiliser sans peur d'erreur.

**Comment by thomasgericot** [comment]
Je sais bien
Je vous demandais juste de confirmer ma réflexion, qui est relative à un
élément essentiel du tp.


Le jeu. 26 mars 2020 à 15:32, guyfrancoeur <notifications@github.com> a
écrit :
