### ISSUE TITLE
TP2 : Valeurs par défaut et tolérances entre des capteurs

### ISSUE THREAD

**Issue by benoit-dubreuil** [guyfrancoeur/INF3135_H2020#163]
Bonjour,

Si, au tout début du programme, la ligne 
```
142 02 A1 15
```
est reçue. Étant donné que les capteurs `A2` et `A3` ont des valeurs par défaut, j'estime qu'il ne faut pas vérifier la tolérance des angles. De plus, étant donné qu'il n'y a pas eu d'entrée pour définir l'état de l'avion, j'estime que l'état est TARMAC (pour parker au sol) et donc je peux vérifier l'angle d'incidence.

Est-ce correct selon vous?

**Comment by Marie287** [comment]
Non , je pense qu'il ne faut pas calculer la tolérance des angles, puisque A2 et A3 n'ont toujours pas de valeurs, donc tu ne peux pas encore les comparer. Si la valeur d'un capteur est sa valeur par défaut, ça veut dire que le capteur n'a pas de valeur enregistrée. C'est juste un indicateur. En aucun cas il faut utiliser cette valeur pour faire des calculs.  
En ce qui concerne l'état par défaut, je sais pas trop si il faut penser comme ça. Même si ça parait logique de le mettre au TARMAC par défaut.  

On pourrait aussi dire que tant que l'état ne sera pas défini, on ne calcule pas les angles d'incidences, puisque c'est un critère pour utiliser ces fonctions là. C'est noté nulle part dans l'énoncé qu'il faut mettre l'état au TARMAC par défaut. Moi je ferait plutôt comme ça.

**Comment by guyfrancoeur** [comment]
Allo,

@Marie287 TARMAC est le default selon l'énoncé.

@benoit-dubreuil , @Marie287 à raison dans l'application des règles de validation.

> > `M` Non , je pense qu'il ne faut pas calculer la tolérance des angles, puisque A2 et A3 n'ont toujours pas de valeurs, donc tu ne peux pas encore les comparer. Si la valeur d'un capteur est sa valeur par défaut, ça veut dire que le capteur n'a pas de valeur enregistrée. C'est juste un indicateur. En aucun cas il faut utiliser cette valeur pour faire des calculs.

voir #160

**Comment by RmannDev** [comment]
le #160 ne donne pas les valeurs par défaut des capteurs .....

**Comment by guyfrancoeur** [comment]
Allo,

@RmannDev  prend une décision, décide toi même de tes variables par défaut.
