### ISSUE TITLE
TP2 : make employé seul

### ISSUE THREAD

**Issue by AdelOuldzeid** [guyfrancoeur/INF3135_H2020#165]
Bonjour

Lorsqu'on saisi la commande make, elle éxecute la cible default qui est dépendante de la cible tp2.

Est ce que ça revient au même que de faire make tp2?

Si tel est le cas, pourquoi ne pas faire de la cible tp2 la première cible dans notre Makefile.

Merci d'avance.

**Comment by Gawonou** [comment]
Oui, je pense que si tu fais la première cible tp2 et le problème est réglé.

**Comment by ac191063** [comment]
Bonjour,

En effet, sachant que l'exécution de la commande `make` exécute la première cible de notre fichier Makefile, mettre la cible `tp2` en premier dans notre fichier Makefile est équivalent à faire une cible `default` ayant comme unique dépendance la cible `tp2`. À l'exécution, la commande `make`, `make tp2` et `make default` auront le même effet, qui est de construire l'exécutable `tp2`.

Je me suis donc posé à peu près la même question : 

Faut-il nécessairement une cible `default` à ce moment la? De plus, est-ce que la cible `default` à comme seul dépendance la cible `tp2`, autrement dit voulons-nous construire uniquement l'exécutable `tp2` avec la commande `make` ou l'exécutable `tp1` doit aussi être construit suite à la commande `make`?

Merci d'avance pour vos réponses,

Cordialement.
