### ISSUE TITLE
TP2: malib.h/c

### ISSUE THREAD

**Issue by Sami-2016** [guyfrancoeur/INF3135_H2020#166]
Bonjour @guyfrancoeur ,

Concernant les fichiers malib.h/c , vous avez écris : "Vous pouvez mettre ce que vous voulez dans les fichiers. Ils ont pour but de rendre le tp2.c plus léger"...

Je ne comprends pas ce qu'on doit mettre au juste dans ces deux fichiers.

Merci à l'avance pour la clarification!

**Comment by link852258** [comment]
Tu peux mettre tes méthodes et les signatures de tes méthodes dans les fichiers respectifs.

**Comment by Sami-2016** [comment]
Merci beaucoup!
