### ISSUE TITLE
TP2: Règle A11

### ISSUE THREAD

**Issue by link852258** [guyfrancoeur/INF3135_H2020#167]
Bonjour,
lorsqu'on dit qu'il faut remettre le capteur à la valeur par défaut, est-ce qu'il faut aussi réinitialiser le nombre d'erreur de ce capteur?
Merci
EX:
```
1 02 A1 ERROR
2 02 A1 ERROR
3 02 A1 -10.000 //valeur inacceptable doit être entre [0-360]
```
A1 = valeur par défaut
le capteur A1 tombe a zéro ERROR à la place de deux.

**Comment by guyfrancoeur** [comment]
Bonjour,

Il y a qq points dans ta questions je ne sais pas quoi dire.

Exemple est bon mais la description est fausse.
La valeur par défaut concerne les anomalies de valeurs. il n'y a pas ca dans ton exemple.
Les nombres d'erreur concerne le MOT `ERROR`.

Au temps  3 le `Compteur de nombre capteur` devient zéro OUI.

Relire enoncé et #160 svp. Je vais fermer cette question.
