### ISSUE TITLE
TP2 : Traitement du mot ERROR pour un capteur

### ISSUE THREAD

**Issue by bachmaroua** [guyfrancoeur/INF3135_H2020#168]
pour la Lecture d'un capteur de l'angle stabilisateur horizontal et  Lecture de longueur de l'ouverture d'un volet 
on doit réagir a la la troisième manifestation de ERROR pour tout les capteurs

176 04 D ERROR
178 04 G ERROR
179 04 D ERROR

06 12 179 3X

ou bien il faut que ca soit pour le meme capteur
176 04 D ERROR
178 04 D ERROR
179 04 D ERROR
06 12 179 3X

et pour la Lecture d'un capteur d'angle d'incidence
si les trois capteur A1, A2 , A3 

180 02 A1 ERROR
181 02 A2 ERROR
199 02 A3 ERROR
est ce que c'est tous le systeme qui doit etre mis en ERROR
06 13 199
avec 
09 MCAS OFF.

ou il faut que ca soit pour chaque capteur 
180 02 A1 ERROR
181 02 A1 ERROR
199 02 A1 ERROR
06 13 199

**Comment by guyfrancoeur** [comment]
Allo,

Même capteur, similaire à ceci :
 - il peut y avoir d'autres transactions de d'autres types dans le lot. 
```
...
176 04 D ERROR
178 04 D ERROR
179 04 D ERROR
...
180 02 A1 ERROR
181 02 A1 ERROR
199 02 A1 ERROR
...
181 03 G ERROR
182 03 G ERROR
183 01 1
184 03 G ERROR
...
```

Voir règle A15 #160

**Comment by Marie287** [comment]
Si je comprends bien, avec les modifications que vous venez d'ajouter, le message ```09 MCAS OFF``` ne s'affichera que si il y a deux trx 08 ? Donc deux fois le même problème de 3X le mot ```ERROR```, et il faudrait qu'ils soient **consécutifs** , et toujours pour le **même capteur** ?

Mais du coup, je me pose une autre question.
Avant vos modifications, lorsqu'un capteur affichait trois fois le mot ```ERROR```, le MCAS devenait OFF. Et pour que le système redevienne opérationnel, il suffisait que le capteur en erreur, redonne **1** valeur acceptable.

Après vos modifications, je me demande si je dois toujours raisonner de la même façon ?
Je pense que oui, mais je doute un peu.

Pareil pour toutes les autres trx 08 en général. Elles sont produites à cause d'une valeur inacceptable. Le MCAS devient OFF lorsque deux valeurs sont inacceptables pour un même système et consécutivement. 
Donc pour remettre le MCAS à ON il suffirait que'un des capteur du système redonne **1** ou bien **2** valeurs acceptables pour rendre le système de nouveau opérationnel ?
Puisque tous les problèmes qui mettent le MCAS à OFF, doivent pouvoir être corrigés ensuite pour pouvoir remettre le MCAS à ON.

**Comment by guyfrancoeur** [comment]
Ceci simplifie le cas du MCAS OFF.

> > `MB` Si je comprends bien, avec les modifications que vous venez d'ajouter, le message 09 MCAS OFF ne s'affichera que s’il y a deux trx 08 ? Donc deux fois le même problème de 3X le mot ERROR, et il faudrait qu'ils soient consécutifs , et toujours pour le même capteur ?

Comment est-ce possible si le défaut est affecté lors de la troisième apparition du mot ERROR ?

Il n'y a pas de lien entre 08 et MCAS OFF.

Je vais accepter les deux façons de faire.

> > `MB` Mais du coup, je me pose une autre question. Avant vos modifications, lorsqu'un capteur affichait trois fois le mot ERROR, le MCAS devenait OFF. Et pour que le système redevienne opérationnel, il suffisait que le capteur en erreur, redonne 1 valeur acceptable.

Voilà pourquoi j'ai simplifié le cas.  Choisir le plus simple est une bonne idée. Il n'est plus nécessaire de gérer le MCAS OFF pour ce cas unique.

En conclusion, vous avez aussi compris que le 3X ERROR est un cas particulier que je risque de tester de façon particulière et simplement sans ambigüité.  Tous les scénarios seront assez simples et sans ambigüité.  Et il y aura beaucoup de scénarios.

Voir #160 pour les valeurs inacceptables.

G

**Comment by Marie287** [comment]
> Comment est-ce possible si le défaut est affecté lors de la troisième apparition du mot ERROR ? 
 
C'est vrai, j'avais complètement oublié de penser à ça. Ça parait évident maintenant pour ce cas ci, merci.  
Donc cela fonctionne de la même manière pour les autres transactions 08 ?  
Puisque selon la règle A11, lorsqu'un capteur produit une transaction 08, alors le capteur est réinitialisé avec sa valeur par défaut. 

> Il n'y a pas de lien entre 08 et MCAS OFF.  

Ceci s'applique uniquement au cas 3X ERROR ? 

Excusez-moi encore, mais je n'arrive toujours pas à comprendre le lien avec cette partie de l'énoncé : lorsqu'un système produit deux transactions 08, le MCAS devient OFF :  
> Pour savoir si on ferme le MCAS, valider avec le maximum de données (**2 valeur** pour VOLET, AI, SH).   

Donc pour ré ouvrir le MCAS, il faut valider **deux** valeurs également ?

**Comment by guyfrancoeur** [comment]
Allo,

Oui pour réouvrir MCAS il faut deux valeurs et un parcourt sans erreur. Pas d'erreur marge ni d'erreur de conformité, etc, etc ... si autre chose il y a.

> > Ceci s'applique uniquement au cas 3X ERROR ?

non, exemple `100 02 A1 1007.1`  
 - produit un `08` et aucune sortie `09 MCAS OFF`

Et bien un `08` ne produit pas de 09 MCAS OFF. Je crois qu'un cas existait mais je l'ai simplifié pour vous.

**Comment by Marie287** [comment]
Oui d'accord, je comprends mieux.
Merci beaucoup pour votre réponse, j'y vois plus clair maintenant. Merci.
