### ISSUE TITLE
TP3: Plus d'informations ?

### ISSUE THREAD

**Issue by TringaAxel** [guyfrancoeur/INF3135_H2020#170]
Allô j'espère que vous allez bien !   

Je voulais savoir quand est-ce que le fichier ***tp3.zip*** va être disponible ?

De plus il est stipulé que le fichier ***tp3.c*** doit contenir qu'une seule fonction main, j'en déduit donc que l'on doit exécuter le programme tp3 dans le fichier ***tp2***. 

Si je ne dis pas de bêtise, nous prenons en arguments dans le fichier tp2, dans lequel nous le faisons passer dans le fichier tp3 ? Et dans les exemples d'exécution vous n'avez jamais marqué ***./tp3*** donc vous allez continuez à exécuter ***./tp2*** uniquement ou bien c'est un oubli ? 

Puis pour ce qui est des fichiers malib, à quoi correspond la fonction cmd ? 
C'est tu afficher le nombre total au tout début de l'affichage, bien avant l'affichage des trx 06 etc ... ? 

> Compter, maintenir et afficher le nombre de lignes les informations demandées au lancement du logiciel.

Merci d'avance !

**Comment by hydraslahir** [comment]
Quote 
**Le fichier tp2.c et tp3.c sont indépendants.**
> Ce travail est une modification du tp2 vous devez donc modifier ce que vous avez déjà.

>Le programme exécutable peut être lancé en ligne de commande avec différentes syntaxes :
$ ./tp2
...
$ ./tp2 -t -d

**Je crois que tu modifies directement le TP2 pour faire ton TP3.**
Néanmoins, comme tu disais, il y a une jolie incohérence
> Un fichier tp3.c contenant votre fonction main;

Néanmoins, pour l'instant je te conseille de copier tp2.c dans tp3.c et modifier tp3.c.
Ça te laisse tp2.c intact et permet de continuer à travailler sur tp3.c
Tu peux toujours renommer tp3.c si besoin.

### cmd
int cmd(...) est une fonction pour traiter les options (-i, -d, -...).

>  Vous ajouterez une fonction de gestion des arguments (options) de la ligne de commande.

Aucune mention de comment l'utiliser concrètement ou de ce qu'il veut de cette méthode.
Tu traites tes options en dehors du main avec la méthode. Il ne devrait pas y avoir de traitement d'options dans ton main.
À toi de voir comment tu vas l'utiliser.

**Comment by cryptoswarm** [comment]
Je pense qu'on aura plus de tp2. 

> Le rôle de votre programme est de lire des transactions (déjà fait tp2). Le tp3 ajoute une fonctionnalité ...
je pense qu'on doit modifier le tp2.c `mv tp2.c tp3.c` ajouter du code dans le `tp3.c` qui est censé  satisfaire les exigences. 

> exemple avec les options -t -i -d -s 
ton tp2 donnait des output des trx de `06 à 09` or avec `-t` on aura plus d'affichage.

**Comment by guyfrancoeur** [comment]
Bonjour,

Consultez l'énoncé pour les ajustements et corrections de coquilles. 

Merci Axel, et les autres.

G

**Comment by benoit-dubreuil** [comment]
Je me pose la même question pour le tp3.zip.

**Comment by guyfrancoeur** [comment]
Allo,

N'attendez pas après moi, trouver une alternative.

G

**Comment by RmannDev** [comment]
Qu'est-ce que ca veut dire ??
> De plus il est stipulé que le fichier tp3.c doit contenir qu'une seule fonction main, j'en déduit donc que l'on doit exécuter le programme tp3 dans le fichier tp2.

**Comment by benoit-dubreuil** [comment]
> Qu'est-ce que ca veut dire ??
> 
> > De plus il est stipulé que le fichier tp3.c doit contenir qu'une seule fonction main, j'en déduit donc que l'on doit exécuter le programme tp3 dans le fichier tp2.

Ce n'est pas vrai, ne te fies pas à ça.

**Comment by RmannDev** [comment]
ok Merci @benoit-dubreuil
