### ISSUE TITLE
AFFICHAGE : le dernier ts lu [TP3]

### ISSUE THREAD

**Issue by Denowrrz** [guyfrancoeur/INF3135_H2020#171]
Juste pour confirmer, quand on affiche 

"le dernier ts lu : xx"       ( -d )

on affiche bien le dernier ts **valide** lu ? 

Merci

**Comment by Marie287** [comment]
Je pense que c'est le bon raisonnement.
Surtout que normalement la valeur d'un timestamp non valide ne devrait pas être retenue en mémoire.
Et puis si la valeur a été lue par le programme, c'est que la lecture s'est bien passée, et que les tests de validité ont été réussi.

**Comment by cryptoswarm** [comment]
> on affiche bien le dernier ts valide lu ? 

On affiche le dernier ts lu.  valide/invalide on s'en fiche. on veut savoir qu'on est rendu à la dernière transaction.

**Comment by benoit-dubreuil** [comment]
J'ai pris en note la même chose que @cryptoswarm sauf que je me demande si on doit quand même prendre en compte si le dernier timestamp est plus petit que le dernier?

Par exemple : 
```
230 03 D 2
01 03 D 2
```

Je comprends que si la 2e ligne était invalide en terme du code trx ou des valeurs lues je considérerais le timestamp pareil, mais je ne sais pas si c'est le cas pour si le dernier timestamp lui-même n'est pas bon. Mon guess est que oui, il faut le garder.

**Comment by cedricwtkUQAM** [comment]
"Dernier ts lu" vs "Dernier ts valide". Fiez vous a l'énoncé.

**Comment by guyfrancoeur** [comment]
Allo,


> Je comprends que si la 2e ligne était invalide en terme du code trx ou des valeurs lues je considérerais le timestamp pareil, mais je ne sais pas si c'est le cas pour si le dernier timestamp lui-même n'est pas bon. Mon guess est que oui, il faut le garder.
> 
> C'est la même chose pour le `-s` : est-ce que `nbr trx (total)` inclus les mauvais trx? Par exemple : `123 00 D 2`?

Oui, Le total include les tx non valides. (nombre total de lignes reçues  avec des données)

Petit bonus, non valide, on regarde seulement le code de tx. Nous ne validons pas le reste après le code de tx.

Je ne me souviens pas si j'avais répondu ceci dans le cadre du cours.

voila.

G
