### ISSUE TITLE
Longueur main() dans tp3.c

### ISSUE THREAD

**Issue by YounesJulien** [guyfrancoeur/INF3135_H2020#172]
Bonjour,

Dans mon tp2.c j'ai créer la grande majorité de mon code dans le main() (750 lignes) avec 4 petite fonctions. 

Est ce je suis obliger de procéder à un refactoring de mon code ou bien je ne serai cautionner sur la longueur de mon main que dans le tp2 soumis il y a 10 jours?

**Comment by guyfrancoeur** [comment]
Bonjour,

Je n'ai sûrement pas de bonne réponse pour cette question. Je crois plutôt que vous savez la réponse, car vous demandez! 

@tous,

Je voudrais plutôt savoir si dans les cours préalable et précédent (dans le temps) INF3135, n'avez-vous pas eux des informations ou directives qui disaient que les fonctions ne devaient pas avoir plus de X lignes ? Si c'est le cas, pourquoi une fonction main( ) de 100+ lignes ?

Questions :
 - int main( ) est-ce une fonction ?
 - Est-ce correct de tout oublier de cours en cours ?
 - N'ai-je pas déjà dit qqc comme : il faut limiter le nombre de lignes d'une fonction ?
 - N'est pas une bonne pratique de faire des fonctions dites atomiques (qui font une chose) ?
 - Comment est-ce possible de ci-retrouver ?
 - Avez-vous seulement une pièce dans votre maison ? 
   + Tout est dans la cuisine ? Même la chambre ?

Je ne vous demande, ne vous dit pas quoi faire de facon explicite, mais la logique et la prise de décision est un élément important de ce cours.  Savoir programmer n'est pas de savoir replir des fichiers de codes, c'est plutot, selon moi, de savoir pourquoi nous écrivons du (le) code.

Le nombre de ligne dans une fonction est une directive implicite.

Finalement rappelez-vous pour qui vous faites le code.

Vous codez pour qui ?
 - Autruit (ceux qui seront impactés)
   + 1. Usagers
   + 2. Clients
   + 3. Collègues
   + 4. Sciences (héritage)
   + 5. Employeurs

Merci pour le commentaire,  je voulais écrire moins mais le sujet est hautement pédagogique.

Coridalement,

G
