### ISSUE TITLE
TP3: timestamp invalide

### ISSUE THREAD

**Issue by leopoldmaillard** [guyfrancoeur/INF3135_H2020#173]
Bonjour,
J'espère que vous vous portez tous bien. 

Un timestamp invalide est défini ainsi dans l'énoncé : ```Lorsque le timestamp est inférieur au temps précédent```. Cela laisse penser qu'un timestamp n'est pas valide s'il est **strictement** inférieur au précédent. Cependant, cela ne fait pas beaucoup de sens que 2 transactions aient le même timestamp.

Par exemple :
```
176 04 D ERROR
176 04 G 0.56
```
Le timestamp de la deuxième transaction est-il invalide ?

Merci !

**Comment by Marie287** [comment]
Je pense que la deuxième transaction est tout à fait valide.  
Il est possible que plusieurs messages d'erreur arrivent en même temps.   
 
Du coup, un timestamp n'est pas valide s'il est strictement inférieur au précédent, oui.

**Comment by leopoldmaillard** [comment]
Merci pour ta réponse @Marie287 
Je suis d'accord avec toi, mais on peut aussi penser que le timestamp sert à identifier une unique transaction. En outre, le système traite bien les transactions les unes après les autres...

Les 2 possibilités ont du sens, il nous faudrait une convention :)

**Comment by MaximCrudu** [comment]
À mon avis, il vaut mieux laisser comme c'est déjà le cas, c'est-à-dire la possibilité d'avoir plus de transactions pour le même timestamp que de poursuivre l'objectif d'avoir un timestamp unique et d'invalider beaucoup de transactions valides simplement parce qu'elles viennent relativement en même temps .

**Comment by benoit-dubreuil** [comment]
J'avais compris la même chose que toi au TP2, jusqu'à temps que je regarde avec plus de précision les exemples du prof. Oui, le mot `ID` porte à confusion, sauf que ce n'est qu'un timestamp. Imagine si deux sensors rapportent en même temps des données en même temps. Va-t-on ignorer la 2e parce qu'elle a le même timestamp? Non. C'est sûr qu'en vrai vie ce serait plus complexe.

**Comment by leopoldmaillard** [comment]
Merci à tous pour vos réponses !

**Comment by JonPhno** [comment]
Bonjour, je ne suis pas certain de savoir quoi faire lorsque nous recevons un timestamp plus petit que celui courant. Est-ce que je devrais remplacer celui courant par le plus petit ou je laisse celui en place ?
