### ISSUE TITLE
TP3: trx valide/invalide

### ISSUE THREAD

**Issue by JonPhno** [guyfrancoeur/INF3135_H2020#174]
Bonjour,

Quand est-ce que ne devrions considérer un tx invalide ou valide ? 
Est-ce qu'un trx est invalide seulement lorsque la valeur associé est invalide ?
ex:
1979998 01 9

Et/ou on le considère invalide s'il cause un erreur système même si sa valeur est valide
ex:
144 02 A1 12.125
145 02 A2 24.250
qui a deux valeur possible pour le capteur, mais génère une erreur système car la marge n'est pas respecté ?

Merci

**Comment by cedricwtkUQAM** [comment]
TRX invalide lorsque le trx est different de 1,2,3,4 et 5. @guyfrancoeur  pouvez vous confirmer?

**Comment by MaximCrudu** [comment]
Selon l'exemple de l'énoncé, on voit que  **nbr trx (total) : 40**  et  **nbr trx valides : 25**, dans la section  **information invalide** on a  **trx non reconnue : 10** et **trx avec ts non sequentiel : 5**

**Comment by JonPhno** [comment]
Ah oui ça fait bien du sens @MaximCrudu
