### ISSUE TITLE
TP3 : fichier tp3.zip

### ISSUE THREAD

**Issue by michaeljamestse** [guyfrancoeur/INF3135_H2020#175]
Bonjour,

Pour la section _make lib_, on donne le URL pour tp3.zip, cependant il n'existe pas encore. Doit-on rediriger la commande make vers ce lien ou bien le dossier parent?

Merci

**Comment by kicak2009** [comment]
Bonjour,

En attendant que le fichier tp3.zip soit disponible, vous devez prendre tp2.zip à la place. C'est mieux que rien!

Bonne journée.

**Comment by kegosu** [comment]
Normalement, ça ne sert à rien d'avoir un tp3.zip vu que tout le code fonctionne très bien avec tp2.zip.
