### ISSUE TITLE
Question: décompression Fichiers

### ISSUE THREAD

**Issue by LorenaMedina** [guyfrancoeur/INF3135_H2020#18]
Le fichiers décompressés doivent rester aussi dans le dossier Data?. Merci.

**Comment by guyfrancoeur** [comment]
Bonjour,

Idéalement, pour facilité la compilation, il est souhaitable de copier (bouger) les fichiers vers votre répertoire de travail.
Le repertoire `./data` est utilisé pour recevoir le zip et faire la décompression.
Disons que `./data` est utilisé uniquement pour cet aspect dans le `tp1`.

Merci,

Réagissez a ce post.
