### ISSUE TITLE
Question: Téléchargement et décompression des Fichiers

### ISSUE THREAD

**Issue by LorenaMedina** [guyfrancoeur/INF3135_H2020#19]
On doit permettre les messages affichés par default (erreurs et succès) sur le terminal, ou de façon silencieuse? .  Merci.

**Comment by guyfrancoeur** [comment]
Allo,

Comme tu veux. Ceci est votre décision.
### Faits:
 - Dans la vie je commence avec le mode verbeux vers plus silencieux.
 - Mes commandes deviennent plus silencieuse au fur et à mesure de la confiance que j'ai.

Dans ce cours vous aurez à prendre des décisions et mesurer les impacts de celles-ci.  Je ne vais pas toujours répondre.  Il est important de vous faire confiance.

Merci pour la question.

Réagisez a ce post.
