### ISSUE TITLE
Question: fonction "angle_incidence_marge_vX"

### ISSUE THREAD

**Issue by LorenaMedina** [guyfrancoeur/INF3135_H2020#20]
Pour l'évaluer, est-ce qu'il y a un critère de tolerance entre les valeurs des deux capteurs?
Dans le fichier flop.h , C'est indiqué "Les valeurs ne sont pas trop éloignées l'une de l'autre.
Merci.

**Comment by guyfrancoeur** [comment]
Bonjour,

J'ai modifié l'énoncé pour la tolérance entre les valeurs fournies par les capteurs d'angle d'incidence.

Merci pour votre vigilance, Bravo.

réagissez à ce post :wink:
