### ISSUE TITLE
volet_angle_conforme_v1 dans flop.h

### ISSUE THREAD

**Issue by kegosu** [guyfrancoeur/INF3135_H2020#25]
Bonjour, est ce qu'on doit dé-commenter les 3 versions de la fonction  "volet_angle_conforme_v1" vu qu'il y a un todo en commentaire par dessus? et après l'avoir utilisé pour les tests et en le compilant, ça affiche une erreur de référence indéfini vers cette fonction. Est ce qu'il y a du code correspondant qui manque dans flop.o? et sinon on n'a pas les valeurs du volet angle conforme sécuritaire sur l'énoncé du tp.
merci

**Comment by lachalex** [comment]
Bonjour, 
    Il ne faut pas toucher à ces fonctions pour le tp1, vous n'avez donc pas besoin des valeurs d'angle du volet.

**Comment by guyfrancoeur** [comment]
Bonjour,

J'ajouterais ceci : vous n'avez pas à modifier les fichiers fournis.
  - il ne faut pas modifier le .o et le .h

Merci.
