### ISSUE TITLE
Quelles exécutions de liste.sh ?

### ISSUE THREAD

**Issue by TringaAxel** [guyfrancoeur/INF3135_H2020#31]
Allô !
Pour plus de clarification sur la base de quel ligne de commande le script liste.sh va être exécuté?

```
./tp1 | ./liste.sh
```
ou 
```
./liste.sh tp1
```
ou 
```
./liste.sh
```
Suivant chaque cas, le script va légèrement changer a chaque fois.

**Comment by lachalex** [comment]
Bonjour,
      l'énoncé du tp1 indique:

       "Le fichier nommé liste.sh recevra par stdin le stdout de tp1."

       il n'y a qu'une seule façon de faire ça.
