### ISSUE TITLE
Installation CUnit machine local

### ISSUE THREAD

**Issue by JonPhno** [guyfrancoeur/INF3135_H2020#38]
Bonjour,

Est-ce que quelqu'un aurait réussi à insaller CUnit sur sa machine locale pour développer? Je ne réussi pas à trouver de guide qui fonctionne de mon côté.

Merci

**Comment by lachalex** [comment]
Bonjour,
      Je réponds à vous mais c'est aussi d'intérêt général.

      cUnit est installé sur le serveur Java de l'UQAM. Vous n'avez qu'a le compiler tel qu'indiqué dans code/cUnit.md du site du cours (github).

      Conseil amical: ne perdez pas de temps à configurer vos machine pour développer dessus, ce cours est bien assez chargé comme ça! De plus vous risquez d'avoir une différence entre votre installation et celle du serveur Java, n'oubliez pas que la correction de vos TP se feront sur le serveur Java.

      Notez que le nom "Java" donné au serveur n'a rien à voir avec le langage de programmation du même nom.
