### ISSUE TITLE
.o

### ISSUE THREAD

**Issue by thomasgericot** [guyfrancoeur/INF3135_H2020#39]
Bonjour, 
je ne vois pas comment changer l'extension du fichier flop.o en un format lisible ? 
Pouvez vous m'aiguiller ?

**Comment by lachalex** [comment]
Bonjour,
    tu dois le compiler avec ton tp. 
    Je t'invite à relire les notes 03-compilation-automatisation.

**Comment by thomasgericot** [comment]
Bonjour,
Je bloque sur un dernier point qui m'empêche de finir le tp.
Pour compiler mon tp en tenant compte des fonctions CU_ASSERT_EQUAL, j'ai
fais ce Makefile:

tp:tp.c flop.o

          gcc -Wall -I/usr/include/CUnit -L/usr/lib64 -lcunit tp tp.c flop.o


et ça m'affiche que dans ma fonction main, il n'y a pas de référence
définie vers "CU_ASSERT_EQAUL".

Pouvez vous m'aiguillez sur le chemin à prendre pour résoudre ce problème ?

Merci et bonne journée,

Thomas Gericot.

**Comment by guyfrancoeur** [comment]
Bonjour,

Premierement je crois qu'il y a des erreurs dans la syntaxe ou des elements à changer :
 + CU_ASSERT_EQUAL (avez-vous essayé autre choses tel que CU_ASSERT_TRUE ?
 + voici ma proposition pour le compilateur :
     - gcc -std=c11 -Wall -I/usr/include/CUnit -L/usr/lib64 -o tp tp.c flop.o -lcunit

@TOUS 
 + Il est important de partager vos dépôts pour des demandes d'assitance spécifique.
 + 

Coridalement,

G
 
Réagisez à ce post svp.

**Comment by lachalex** [comment]
> Il est important de partager vos dépôts pour des demandes d'assitance spécifique.

Uniquement avec Guy ou moi, pas avec vos collègues. Ne rendez pas vos dépôts publics!

**Comment by thomasgericot** [comment]
Merci pour la réponse
J’ai rajouté un include dans mon tp.c qui a résolu le problème
Merci !

**Comment by thomasgericot** [comment]
J'ai mis à jour mon dépôt à distance, merci pour le conseil

Le ven. 7 févr. 2020 à 15:03, Gericot thomas <tomtomgericot@gmail.com> a
écrit :
