### ISSUE TITLE
liste.sh en stdout ou dans un fichier ?

### ISSUE THREAD

**Issue by AlexandreBillereau** [guyfrancoeur/INF3135_H2020#47]
Le fichier nommé liste.sh recevra par stdin le stdout de tp1. Par la suite, vous devez lister uniquement les noms des fonctions qui sont valides et fonctionnelles. Il y aura certainement ...

Dans l'énoncé il n'est pas precisé si liste.sh doit ecrire dans un fichier ou l'afficher dans la sorti standar. 

j'imagine que ce sera dans la sorti standar mais c'est pour etre sur merci d'avance.

**Comment by guyfrancoeur** [comment]
Bonjour,

Oui,

Le default est stdout, lorsque non specifié.
Nous n'avons pas besoin de plus n'est pas ?

Merci,

G
