### ISSUE TITLE
STDOUT

### ISSUE THREAD

**Issue by Fadhel-Smari** [guyfrancoeur/INF3135_H2020#54]
salut,
le programme doit afficher dans le terminal le stdout de l'exécutable tp1 et apres le stdout de liste.sh
ou juste le stdout de liste.sh ?
MERCI

**Comment by guyfrancoeur** [comment]
Bonjour,

Tout d'abord attention au duplicata de questions et au français de celle-ci.

Voici : 
1. Nous allons faire un retour sur les bases du système Linux;
2. Nous allons faire un retour stdin et stdout;
3. Nous allons faire un retour le tube dans l'environnement Linux;

Concernant la question, est-ce possible de fournir un exemple de ce que tu demandes.

Ma question est la suivante comment est-ce possible de faire ce qui est demandé dans ta question?

Cordialement,

GF

**Comment by Fadhel-Smari** [comment]
bonjour,
J'ai mal posé la question , je demande ce que doit s' afficher dans la console lorsqu'on exécute la commande make test 
est ce que cette commande doit lister uniquement les noms des fonctions qui sont valides et fonctionnelles ?
MERCI

**Comment by guyfrancoeur** [comment]
Allo,

Mes questions : 
 + est-ce possible d'afficher les deux ? facilement ? comment ?
 + est-ce que liste.sh est utilisé dans votre `make test` ?

Idéalement la cible test doit produire uniquement les noms des fonctions qui sont parfaites.

Ceci dit, vous pouvez creer des cibles additionnelles qui test et valides d'autres choses.

Cordialement, 

GF

**Comment by Fadhel-Smari** [comment]
Salut,
J'ai pas essayé d'afficher les deux ,je sais pas si c'est possible .
Oui j'ai utilisé liste.sh dans make test et le test affiche uniquement les noms des fonctions qui sont parfaites.
MERCI

**Comment by benoit-dubreuil** [comment]
> Idéalement la cible test doit produire uniquement les noms des fonctions qui sont parfaites.

Intéressant, même en relisant plusieurs fois l'énoncé, j'étais certain que `make test` ne devait qu'afficher l'output de CUnit et que c'était à l'utilisateur d'utiliser manuellement `liste.sh`.

Je pense que je suis mélangé par le fait que les explications sont à la 3e personne, i.e. 
> Votre programme exécutable tp1 liste beaucoup de choses lorsqu'il est lancé. **Le fichier nommé liste.sh recevra par stdin le stdout de tp1.** Par la suite, vous devez lister uniquement les noms des fonctions qui sont valides et fonctionnelles. Il y aura certainement plusieurs fonctions qui vont être listées.

Je pensais que quand vous disiez que 
> vous devez lister uniquement les noms des fonctions qui sont valides et fonctionnelles
ça n'incluait que le script `liste.sh` et donc que `make test` n'avait pas à l'appeler.
