### ISSUE TITLE
Plusieurs version de fonction valide

### ISSUE THREAD

**Issue by Alexisbou** [guyfrancoeur/INF3135_H2020#6]
Bonjour, est-il possible que plus d'une version d'une même fonction soit valide? Par ex. tarmac_angle_conforme_v1 et tarmac_angle_conforme_v2?

Merci!

**Comment by guyfrancoeur** [comment]
Bonjour,

À vous de me le dire. Je crois même que c'est le but du tp1, n'est-ce pas ? 
Si c'est le cas je crois que votre programme (de test) sera en mesure d'identifier les fonctions fonctionnelles.

Cordialement,

Réagissez à ce post. :wink:
