### ISSUE TITLE
cUnit

### ISSUE THREAD

**Issue by thomasgericot** [guyfrancoeur/INF3135_H2020#61]
Bonjour, 
Je n'arrive pas à compiler mon tp.c en prenant en compte les ASSERT disponible dans cUnit.
Je suis pourtant les indications présentes sur le fichier CUnit du cours.
Que faut il faire ? 
Merci!

**Comment by guyfrancoeur** [comment]
Allo,

C'est un peu vague comme question.

Mais je peux dire de continuer ou changer la méthode ou l'approche.  Il y a surement un oubli.

@tous
Se lancer dans le code sans avoir compris les notions n'est surement pas une bonne façon de faire.
Vous devez idéalement avoir une stratégie.

Commencer avec les choses simples. (ateliers, exemples vu en cours)
Par la suite faire les travaux.

G

Réagissez à ce post.
