### ISSUE TITLE
Erreur référence indéfinie (cUnit)

### ISSUE THREAD

**Issue by phsoucy** [guyfrancoeur/INF3135_H2020#7]
Lorsque je compile en utilisant la commande suivante (tel qu'indiqué dans cUnit.md) :

`gcc -Wall -I/usr/include/CUnit -L/usr/lib64 -lcunit -o max_test max_test.c max.o`

J'obtiens plusieurs erreurs de références indéfinies, par exemple :

`max_test.c:(.text+0x55) : référence indéfinie vers « CU_assertImplementation »`

Mais lorsque j'utilise la commande suivante :

`gcc -Wall -I/usr/include/CUnit -L/usr/lib64 -o max_test max_test.c max.o -lcunit`

Tout fonctionne normalement. Est-ce que d'autres ont la même chose?

**Comment by guyfrancoeur** [comment]
Bonjour,

Bien que le forum ne soit pas la pour faire du debogage, le debogue doit être fait par l'étudiant sans aide externe.   Je vous demande quand meme de formir un minimum d'information afin de voir comment il est possible de vous aider.

J'ai l'impression d'une mauvaise utilisation de l'exemple.

Exemples :
 - plateforme Linux et version, 
 - Makefile, commandes,
 - msg erreurs 
 - autres..

Cordialement,

**Comment by phsoucy** [comment]
J'ai réessayé directement sur le serveur java en ssh et ça fonctionne. J'étais sur un Ubuntu de l'UQAM quand ça ne fonctionnait pas. Vaudrait-il mieux ajouter `-lcunit` avant le `-o` et le mettre aussi à la fin, de cette façon ça fonctionne dans tous les cas :

```
gcc -Wall -I/usr/include/CUnit -L/usr/lib64 -lcunit -o max_test max_test.c max.o -lcunit
```

**Comment by guyfrancoeur** [comment]
Bonjour,

Merci pour la réponse.  Aucune machine n'est identique, nous en avons la preuve.  J'aime votre expérimentation. Vous en savez deja un peu plus.. 👍 
  
Ca veut aussi dire qu'il ne faut pas : 
 - assumer;
 - laisser les choses au hazard.

Vous avez bien réagit, bravo, on lâche pas.

Cordialement,

**Comment by Marie287** [comment]
Bonjour,

Est-ce que nous devons installer la librairie CUnit sur notre ordinateur personnel pour pouvoir l'utiliser ? Je travaille sur mon TP à l'aide de Putty, et je travaille sur le serveur Java de l'UQÀM.
Mon ordinateur est un Windows.

J'obtiens la même erreur : "référence indéfinie".
J'ai donc essayé d'inclure les paramètres comme indiqué dans le premier message, mais ça ne fonctionne toujours pas. À vrai dire, je ne comprends pas vraiment à quoi correspondent les chemins appartenant au "-I" et "-L". Est-ce qu'ils font référence à un répertoire sur l’ordinateur personnel, ou bien à un répertoire appartenant au serveur de l'UQÀM ?


```
gcc -Wall -pedantic -std=c11 -I/usr/include/CUnit -L/usr/lib64 -lcunit -o tp1 tp1.c
tp1.c: In function ‘main’:
tp1.c:14:2: warning: statement with no effect [-Wunused-value]
  test_fct;
  ^~~~~~~~
/tmp/ccqfjGIN.o : Dans la fonction « test_fct » :
tp1.c:(.text+0xd) : référence indéfinie vers « decollage_angle_conforme_v1 »
collect2: error: ld returned 1 exit status
make: *** [Makefile:2: default] Error 1
```


Bien cordialement.

**Comment by lachalex** [comment]
Bonjour, 
     la fonction decollage_angle_conforme_v1 ne provient pas de cUnit mais de flop.o.
     est-ce que ce fichier est utilisé dans votre processus de compilation?

     Pour le -I et -L: cela correspond à des chemins d'accès sur la machine où a lieu la compilation, donc sur le serveur Java si vous travaillez sur ce serveur via Putty.

**Comment by Marie287** [comment]
Non, je n'utilise pas flop.o lors de ma compilation. J'ai juste importé flop.h dans mon tp1.c
Et c'est le fichier tp1.c que j'exécute.
Il faut donc utiliser flop.o lors de la compilation ?
