### ISSUE TITLE
Branche `testunitaire`

### ISSUE THREAD

**Issue by benoit-dubreuil** [guyfrancoeur/INF3135_H2020#74]
Salut,

Juste pour en être certain, on n'a pas à créer la branche `testunitaire`, right? Il me semble qu'elle sera générer à l'heure de remise par un script de M. Francoeur, mais j'aimerais en être sûr.

Merci

**Comment by wchretien** [comment]
Voir l'issue #14 . Tu dois creer et travailler a l'interieur de celle-ci

**Comment by guyfrancoeur** [comment]
Bonjour,

Bien lire l'énoncé.  Il y va de plusieurs points a prendre. Bonus pour @wchretien .

Cordialement,

G
