### ISSUE TITLE
tp1.depot

### ISSUE THREAD

**Issue by ardofall** [guyfrancoeur/INF3135_H2020#75]
Bonjour,
Ça fait un moment que j’ai ajouté l’utilisateur guyfrancoeur comme collaborateur mais je ne suis toujours pas listé dans tp1.depot. Ça sera réglé avant la remise?

**Comment by wchretien** [comment]
Tu dois l'ajouter comme collaborateur et faire un pull request sur le depot en ajoutant ton repo du projet

**Comment by ardofall** [comment]
Oh c’est parfait merci beaucoup
