### ISSUE TITLE
make test

### ISSUE THREAD

**Issue by djamz47** [guyfrancoeur/INF3135_H2020#80]
Bonjour,  j'aimerais poser une question quant à un détail pour le make test.

Je comprends que le make test doit afficher les fonctions validées grâce au STDOUT du tp1 redirigé en STDIN etc..  Par contre, sans trop entrer dans les détails, nous gérons ceci avec le Makefile.
Vous disiez que chaque cible devrait être responsable d'une seule chose.

Si la cible test s'occupe d'afficher les fonctions validées tel qu'expliqué plus haut, devons-nous gérer   la dépendance TP1 ou pas ?

Je m'explique:

- si le TP1 n'est pas encore compilé et qu'on lance le make test sans dépendance, nous aurons une erreur car on utilise le STD d'un exécutable qui n'existe pas encore.

- si le TP1 n'est pas encore compilé et qu'on lance le make test avec la cible tp1 comme dépendance, nous n'aurons pas d'erreur, mais le test engendra de build une deuxième fois.

* Devons-nous supposer que le make test sera lancé par l'utilisateur seulement après avoir compilé le tp1, ou bien devrions-vous plutôt mettre la dépendance pour être sûr que les 2 situations seront gérées (malgré le fait qu'on devra toujours faire un build de cette façon).

Merci.

**Comment by guyfrancoeur** [comment]
Allo,

Selon toi est-ce que ca va fonctionner si les dépendances ni sont pas?
 + de toute évidance tu as bien réfléchi.

Bravo pour tes efforts.

Cordialement,

G
