### ISSUE TITLE
sortie finale

### ISSUE THREAD

**Issue by thomasgericot** [guyfrancoeur/INF3135_H2020#84]
Bonjour, je sais qu'on en a parlé en cours mais je veux m'assurer de quelque chose.
lorsqu'on exécute tp1, seules les fonctions fonctionnelles doivent s'afficher, ou bien toutes les fonctions ?
Merci !

**Comment by guyfrancoeur** [comment]
Bonjour,

C'est le rôle de `liste.sh`.  Relire énoncé svp.

@thomasgericot  et @tous, je n'ai pas à valider (les travaux) avant la correction.
 + Vous devez lire, comprendre et prendre une décision qui est réfléchie.

Les énoncés sont très claire et précis, si des notions manquent, elles seront certainement ajoutées à l'énoncé, et vous serez référé pour votre contribution.

Corialement,

G
