### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by thomasgericot** [guyfrancoeur/INF3135_H2020#85]
Bonjour, 
Je ne comprend pas ce que doit contenir le fichier gitignore. Faut il inclure dedans tous nos fichiers ? 
Merci!

**Comment by guyfrancoeur** [comment]
Allo,

il s'agit des fichiers ou regEx `*.o` des fichiers a ne pas inclure dans votre dépôt distant.

G

**Comment by thomasgericot** [comment]
Cela inclus seulement les fichiers .o, ou bien aussi les fichiers d'entête?
merci 
T

**Comment by benoit-dubreuil** [comment]
> Votre projet (dépôt distant) ne doit pas contenir de fichiers objet ou binaire.

Habituellement, on ne garde que les fichiers de configuration généraux (qui ne sont pas propre à l'environnement d'un utilisateur) ainsi que le code source. Ça l'inclut les scripts.
