### ISSUE TITLE
dépôt

### ISSUE THREAD

**Issue by thomasgericot** [guyfrancoeur/INF3135_H2020#89]
Bonjour, pouvez vous m'indiquer le chemin à suivre pour rajouter mon projet au dépôt ?
Merci
T

**Comment by benoit-dubreuil** [comment]
Voici ce que l'enseignant a écrit dans ses explications :

> Le nom de votre dépôt doit être `inf3135-h2020-tp1` (en minuscules). Vous devez ajouter l'utilisateur `guyfrancoeur` comme collaborateur. Ceci permettra récupérer et possiblement de déposer qqc commentaires (fichiers) dans votre projet.

Ensuite, pour rajouter ton dépôt à `tp1.depot`, l'enseignant l'a mentionné en classe (ce n'est pas écrit à ce que je sache).
Or, il faut que tu copies l'URL de ton dépôt et que l'ajoutes simplement au fichier https://github.com/guyfrancoeur/INF3135_H2020/blob/master/tp/tp1.depot.
